linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bidichk
    - contextcheck
    - durationcheck
    - errorlint
    - goconst
    - goimports
    - revive
    - ifshort
    - misspell
    - prealloc
    - whitespace
    - wrapcheck

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true