//go:build !js

package crystalline

import (
	"fmt"
	"go/format"
	"go/types"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

// Skipped records something that could not be bound, so that a gap in the
// generated surface is reported rather than silently omitted.
type Skipped struct {
	Name   string
	Reason string
}

func (s Skipped) String() string {
	return s.Name + ": " + s.Reason
}

// GoBindings is the generated binding source for one package.
type GoBindings struct {
	// Package is the name of the package the source belongs to.
	Package string

	// Source is formatted Go, to be written next to the package it binds.
	Source string

	// Skipped lists everything that could not be bound.
	Skipped []Skipped
}

// BuildGo emits reflect-free binding source for everything the loaded manifests
// and directives declare.
//
// packageName is the package the generated file belongs to, and selfPath its
// import path; both refer to a package the consumer owns, since generated code
// cannot be written into a dependency.
//
// The generated code registers through syscall/js directly, so a binary built
// from it does not link reflect at all.
func (g *Generator) BuildGo(declarations Declarations, packageName string, selfPath string) (GoBindings, error) {
	e := &emitter{
		gen:     g,
		pkgName: packageName,
		imports: newImports(selfPath),
		marks:   newMarks(declarations),
	}

	source, err := e.emitBindings(declarations)
	if err != nil {
		return GoBindings{}, err
	}

	formatted, err := format.Source([]byte(source))
	if err != nil {
		return GoBindings{}, fmt.Errorf("generated source is not valid Go: %w\n%s", err, source)
	}

	return GoBindings{
		Package: packageName,
		Source:  string(formatted),
		Skipped: e.skipped,
	}, nil
}

type emitter struct {
	gen     *Generator
	pkgName string
	imports *imports
	skipped []Skipped

	// marks carries the method decisions a manifest declared.
	marks marks

	// marshallers holds the generated struct marshal helpers, keyed by type
	// name so each is emitted once.
	marshallers map[string]string
	pending     []*types.Named

	converters map[string]string
}

func (e *emitter) skip(name string, reason string) {
	e.skipped = append(e.skipped, Skipped{Name: name, Reason: reason})
}

// emitBindings renders the whole generated file.
func (e *emitter) emitBindings(declarations Declarations) (string, error) {
	e.marshallers = make(map[string]string)
	e.converters = make(map[string]string)

	var registrations, wrappers, values strings.Builder

	for _, entry := range declarations.Entries {
		switch entry.Kind {
		case EntryFunc:
			wrapper, err := e.emitDeclaredFunc(entry)
			if err != nil {
				e.skip(entry.Namespace+"."+entry.Name, err.Error())

				continue
			}

			registrations.WriteString("\tcrystallineNamespace(" + strconv.Quote(e.gen.appName) + ", " + strconv.Quote(entry.Namespace) + ").Set(" +
				strconv.Quote(entry.Name) + ", crystallineWrap(js.FuncOf(" + wrapperName(entry) + ")))\n")
			wrappers.WriteString(wrapper)
		case EntryValue:
			branch, err := e.emitDeclaredValue(entry)
			if err != nil {
				e.skip(entry.Namespace+"."+entry.Name, err.Error())

				continue
			}

			values.WriteString(branch)
		case EntryType:
			if named, ok := entry.Type.(*types.Named); ok {
				e.queue(named)
			}
		}
	}

	// Marshallers can queue further marshallers, so drain until stable.
	for len(e.pending) > 0 {
		named := e.pending[0]
		e.pending = e.pending[1:]

		if _, done := e.marshallers[instantiatedName(named)]; done {
			continue
		}

		e.marshallers[instantiatedName(named)] = ""

		body, err := e.emitMarshaller(named)
		if err != nil {
			e.skip(named.Obj().Name(), err.Error())

			continue
		}

		e.marshallers[instantiatedName(named)] = body
	}

	var helpers strings.Builder

	for _, name := range sortedKeys(e.marshallers) {
		helpers.WriteString(e.marshallers[name])
	}

	for _, name := range sortedKeys(e.converters) {
		helpers.WriteString(e.converters[name])
	}

	// The manifests run last, so that every function is already bound by the
	// time a manifest hands over its values.
	var manifests strings.Builder

	for _, manifest := range declarations.Manifests {
		// Generating next to the manifest is the natural layout, and importing
		// your own package is a cycle, so call it unqualified there.
		call := manifest.Name
		if manifest.Package != e.imports.self {
			call = e.imports.add(manifest.Package, lastSegment(manifest.Package)) + "." + call
		}

		manifests.WriteString("\t" + call + "(crystallineRegistry{})\n")
	}

	var out strings.Builder

	out.WriteString("//go:build js\n\n")
	out.WriteString("// Code generated by crystalline. DO NOT EDIT.\n\n")
	out.WriteString("package " + e.pkgName + "\n\n")

	var body strings.Builder

	body.WriteString("func init() {\n")
	body.WriteString(registrations.String())

	if manifests.Len() > 0 {
		body.WriteString("\n")
		body.WriteString(manifests.String())
	}

	body.WriteString("}\n\n")
	body.WriteString(e.emitRegistry(values.String()))
	body.WriteString(prelude)
	body.WriteString(wrappers.String())
	body.WriteString(helpers.String())

	// Imports are collected while rendering, so the block is written last.
	out.WriteString(e.imports.block([]string{contextPackage, "errors", "strconv", "sync", "syscall/js"}))
	out.WriteString(body.String())

	return out.String(), nil
}

// emitRegistry renders the bind.Registry implementation the manifests are
// handed. Functions and marks are resolved statically, so only Value carries
// anything through at run time.
func (e *emitter) emitRegistry(values string) string {
	bindAlias := e.imports.add("github.com/Vilsol/crystalline/bind", "bind")

	var out strings.Builder

	out.WriteString("// crystallineRegistry receives what the manifests declare. Everything but a\n")
	out.WriteString("// value is already bound above, so the rest are no-ops.\n")
	out.WriteString("type crystallineRegistry struct{}\n\n")
	out.WriteString("func (crystallineRegistry) Func(fn any, opts ..." + bindAlias + ".Option) {}\n\n")
	out.WriteString("func (crystallineRegistry) Type(zero any) {}\n\n")
	out.WriteString("func (crystallineRegistry) Ignore(zero any, method string) {}\n\n")
	out.WriteString("func (crystallineRegistry) Promise(zero any, method string) {}\n\n")

	out.WriteString("func (crystallineRegistry) Value(name string, value any, opts ..." + bindAlias + ".Option) {\n")

	if values == "" {
		out.WriteString("}\n\n")

		return out.String()
	}

	out.WriteString("\tresolved := " + bindAlias + ".Resolve(opts)\n\n")
	out.WriteString("\tswitch resolved.Namespace + \"|\" + name {\n")
	out.WriteString(values)
	out.WriteString("\t}\n}\n\n")

	return out.String()
}

// emitDeclaredValue renders the branch that publishes one declared value. The
// key pairs the namespace override with the name, which is exactly what the
// registry can reconstruct at run time.
func (e *emitter) emitDeclaredValue(entry Entry) (string, error) {
	converted, err := e.toJS("typed", entry.Type, false)
	if err != nil {
		return "", err
	}

	goType := types.TypeString(entry.Type, e.qualifier)

	var out strings.Builder

	out.WriteString("\tcase " + strconv.Quote(entry.NamespaceOverride+"|"+entry.Name) + ":\n")
	out.WriteString("\t\ttyped, ok := value.(" + goType + ")\n")
	out.WriteString("\t\tif !ok {\n\t\t\tcrystallineFail(" + strconv.Quote(entry.Name+": expected "+goType) + ")\n\n\t\t\treturn\n\t\t}\n\n")
	out.WriteString("\t\tcrystallineNamespace(" + strconv.Quote(e.gen.appName) + ", " + strconv.Quote(entry.Namespace) + ").Set(" +
		strconv.Quote(entry.Name) + ", " + converted + ")\n")

	return out.String(), nil
}

func lastSegment(path string) string {
	if index := strings.LastIndex(path, "/"); index >= 0 {
		return path[index+1:]
	}

	return path
}

func wrapperName(entry Entry) string {
	namespace := sanitiseAlias(entry.Namespace)
	if namespace != "" {
		namespace = strings.ToUpper(namespace[:1]) + namespace[1:]
	}

	return "crystallineFn" + namespace + entry.Name
}

func marshalName(name string) string {
	return "crystallineMarshal" + name
}

// declaredName renders a type the way generated code must spell it.
func (e *emitter) declaredName(t types.Type) string {
	return types.TypeString(t, e.qualifier)
}

func (e *emitter) emitDeclaredFunc(entry Entry) (string, error) {
	fn, ok := entry.Object.(*types.Func)
	if !ok {
		return "", fmt.Errorf("%s is not a function", entry.Name)
	}

	sig, ok := fn.Type().(*types.Signature)
	if !ok {
		return "", fmt.Errorf("%s is not a function", entry.Name)
	}

	var body strings.Builder

	body.WriteString("func " + wrapperName(entry) + "(this js.Value, args []js.Value) (result any) {\n")
	body.WriteString("\tdefer crystallineRecover(&result)\n\n")
	body.WriteString("\tif len(args) != " + strconv.Itoa(sig.Params().Len()) + " {\n")
	body.WriteString("\t\treturn crystallineFail(" + strconv.Quote(fn.Name()+": expected "+strconv.Itoa(sig.Params().Len())+" arguments, got ") + " + strconv.Itoa(len(args)))\n")
	body.WriteString("\t}\n\n")

	call, preamble, err := e.emitArguments(sig)
	if err != nil {
		return "", err
	}

	invocation := e.qualifier(fn.Pkg()) + "." + fn.Name() + "(" + strings.Join(call, ", ") + ")"

	returns, err := e.emitReturn(invocation, sig.Results())
	if err != nil {
		return "", err
	}

	// The preamble sets up feeds and cancellation whose lifetime is the call,
	// so it belongs inside the promise body. Left in the wrapper, its deferred
	// teardown would run the moment the promise was handed back.
	returns = preamble + returns

	body.WriteString(wrapPromise(returns, entry.Promise || e.gen.isPromise(fn) || hasCallback(sig) || takesContext(sig) || takesChannel(sig), 1))
	body.WriteString("}\n\n")

	return body.String(), nil
}

// wrapPromise defers a rendered body onto a goroutine when the member is
// asynchronous, matching what the declarations promise.
// hasCallback reports whether the signature takes a function, which cannot be
// serviced without yielding to the JS event loop.
// takesContext reports whether the signature starts with a context, which
// forces the call to be asynchronous so the signal can interrupt it.
func takesContext(sig *types.Signature) bool {
	return sig.Params().Len() > 0 && isContextType(sig.Params().At(0).Type())
}

// takesChannel reports whether the signature takes a channel the caller fills,
// which is drained on a goroutine and so cannot be serviced synchronously.
func takesChannel(sig *types.Signature) bool {
	for i := 0; i < sig.Params().Len(); i++ {
		if channel, ok := sig.Params().At(i).Type().Underlying().(*types.Chan); ok && channel.Dir() == types.RecvOnly {
			return true
		}
	}

	return false
}

func hasCallback(sig *types.Signature) bool {
	for i := 0; i < sig.Params().Len(); i++ {
		if _, ok := sig.Params().At(i).Type().Underlying().(*types.Signature); ok {
			return true
		}
	}

	return false
}

func wrapPromise(returns string, promise bool, depth int) string {
	if !promise {
		return returns
	}

	indent := strings.Repeat("\t", depth)

	inner := strings.ReplaceAll(strings.TrimRight(returns, "\n"), "\n", "\n\t")

	return indent + "return crystallinePromise(func() any {\n" + inner + "\n" + indent + "})\n"
}

// emitArguments renders the conversion of every parameter, plus any preamble
// the conversions need.
func (e *emitter) emitArguments(sig *types.Signature) ([]string, string, error) {
	call := make([]string, 0, sig.Params().Len())

	var preamble strings.Builder

	for i := 0; i < sig.Params().Len(); i++ {
		param := sig.Params().At(i)

		// A leading context is driven by an AbortSignal rather than converted.
		if i == 0 && isContextType(param.Type()) {
			preamble.WriteString("\tcrystallineCtx, crystallineStop := crystallineContext(args[0])\n")
			preamble.WriteString("\tdefer crystallineStop()\n\n")

			call = append(call, "crystallineCtx")

			continue
		}

		if channel, ok := param.Type().Underlying().(*types.Chan); ok {
			if err := checkChannelParameter(channel, param.Name()); err != nil {
				return nil, "", err
			}

			converter, err := e.ensureValueConverter(channel.Elem())
			if err != nil {
				return nil, "", fmt.Errorf("channel element: %w", err)
			}

			name := "crystallineFeed" + strconv.Itoa(i)

			preamble.WriteString("\t" + name + ", " + name + "Stop := crystallineFeed(args[" + strconv.Itoa(i) + "], " + converter + ")\n")
			preamble.WriteString("\tdefer " + name + "Stop()\n\n")

			call = append(call, name)

			continue
		}

		expr, err := e.fromJS("args["+strconv.Itoa(i)+"]", param.Type())
		if err != nil {
			return nil, "", err
		}

		call = append(call, expr)
	}

	return call, preamble.String(), nil
}

// emitReturn renders the call and the conversion of its results.
//
// A trailing error becomes a rejection rather than a returned value, matching
// what the declarations promise.
func (e *emitter) emitReturn(invocation string, results *types.Tuple) (string, error) {
	values, fallible := splitError(results)

	total := len(values)
	if fallible {
		total++
	}

	if total == 0 {
		return "\t" + invocation + "\n\n\treturn nil\n", nil
	}

	names := make([]string, total)
	for i := range names {
		names[i] = "r" + strconv.Itoa(i)
	}

	var body strings.Builder

	body.WriteString("\t" + strings.Join(names, ", ") + " := " + invocation + "\n\n")

	if fallible {
		body.WriteString("\tif " + names[total-1] + " != nil {\n\t\treturn crystallineErr(" + names[total-1] + ")\n\t}\n\n")
	}

	if len(values) == 0 {
		if fallible {
			body.WriteString("\treturn crystallineOk(nil)\n")
		} else {
			body.WriteString("\treturn nil\n")
		}

		return body.String(), nil
	}

	converted := make([]string, len(values))

	for i, value := range values {
		expr, err := e.toJS(names[i], value.Type(), false)
		if err != nil {
			return "", err
		}

		converted[i] = expr
	}

	produced := converted[0]
	if len(values) > 1 {
		produced = "[]any{" + strings.Join(converted, ", ") + "}"
	}

	if fallible {
		body.WriteString("\treturn crystallineOk(" + produced + ")\n")

		return body.String(), nil
	}

	body.WriteString("\treturn " + produced + "\n")

	return body.String(), nil
}

// toJS renders a Go expression producing a value js.ValueOf accepts. nonNil
// makes an empty collection stand in for a nil one, honouring the not_nil tag.
func (e *emitter) toJS(expr string, t types.Type, nonNil bool) (string, error) {
	switch typed := t.(type) {
	case *types.Basic:
		return basicToJSExpr(expr, typed)
	case *types.Named, *types.Alias:
		return e.namedToJSExpr(expr, t)
	case *types.Pointer:
		if named, ok := typed.Elem().(*types.Named); ok {
			if _, isStruct := named.Underlying().(*types.Struct); isStruct {
				e.queue(named)

				return marshalName(instantiatedName(named)) + "(" + expr + ")", nil
			}
		}

		// A pointer to anything else is just an optional value.
		inner, err := e.toJS("*"+expr, typed.Elem(), false)
		if err != nil {
			return "", fmt.Errorf("pointer to %s is not supported: %w", typed.Elem(), err)
		}

		return "func() any {\n\t\tif " + expr + " == nil {\n\t\t\treturn nil\n\t\t}\n\n\t\treturn " + inner + "\n\t}()", nil
	case *types.Slice:
		return e.sliceToJSExpr(expr, typed.Elem(), nonNil)
	case *types.Array:
		return e.arrayToJSExpr(expr, typed, nonNil)
	case *types.Interface:
		if isErrorType(t) {
			return "crystallineError(" + expr + ")", nil
		}

		return "", fmt.Errorf("interface %s is not supported", t)
	case *types.Map:
		return e.mapToJSExpr(expr, typed, nonNil)
	case *types.Chan:
		if typed.Dir() == types.SendOnly {
			return "", fmt.Errorf("a send-only channel has no JS counterpart")
		}

		inner, err := e.toJS("item", typed.Elem(), false)
		if err != nil {
			return "", err
		}

		return "crystallineIterator(func() (any, bool) {\n\t\titem, ok := <-" + expr + "\n\t\tif !ok {\n\t\t\treturn nil, false\n\t\t}\n\n\t\treturn " + inner + ", true\n\t})", nil
	}

	return "", fmt.Errorf("un-convertable type: %s", t)
}

func basicToJSExpr(expr string, basic *types.Basic) (string, error) {
	switch basic.Kind() {
	case types.Bool:
		return "bool(" + expr + ")", nil
	case types.String:
		return "string(" + expr + ")", nil
	case types.Complex64, types.Complex128:
		return "", fmt.Errorf("%s cannot be converted to wasm", basic)
	}

	if basic.Info()&types.IsNumeric != 0 {
		return "float64(" + expr + ")", nil
	}

	return "", fmt.Errorf("un-convertable basic type: %s", basic)
}

func (e *emitter) namedToJSExpr(expr string, t types.Type) (string, error) {
	if isErrorType(t) {
		return "crystallineError(" + expr + ")", nil
	}

	named, ok := t.(*types.Named)
	if !ok {
		return e.toJS(expr, t.Underlying(), false)
	}

	if _, ok := named.Underlying().(*types.Struct); ok {
		e.queue(named)

		return marshalName(instantiatedName(named)) + "(&" + expr + ")", nil
	}

	return e.toJS(expr, named.Underlying(), false)
}

func (e *emitter) sliceToJSExpr(expr string, elem types.Type, nonNil bool) (string, error) {
	if basic, ok := elem.Underlying().(*types.Basic); ok && basic.Kind() == types.Uint8 {
		return "crystallineBytes(" + expr + ")", nil
	}

	inner, err := e.toJS("v", elem, false)
	if err != nil {
		return "", err
	}

	empty := "nil"
	if nonNil {
		empty = "[]any{}"
	}

	// Rendered inline so the generated code stays free of generics helpers.
	return "func() any {\n\t\tif " + expr + " == nil {\n\t\t\treturn " + empty + "\n\t\t}\n\n\t\tout := make([]any, 0, len(" + expr + "))\n\t\tfor _, v := range " + expr + " {\n\t\t\tout = append(out, " + inner + ")\n\t\t}\n\n\t\treturn out\n\t}()", nil
}

// arrayToJSExpr renders a fixed size array. Unlike a slice it is never nil, so
// there is nothing to guard.
func (e *emitter) arrayToJSExpr(expr string, typed *types.Array, nonNil bool) (string, error) {
	if basic, ok := typed.Elem().Underlying().(*types.Basic); ok && basic.Kind() == types.Uint8 {
		return "crystallineBytes(" + expr + "[:])", nil
	}

	inner, err := e.toJS("v", typed.Elem(), false)
	if err != nil {
		return "", err
	}

	return "func() any {\n\t\tout := make([]any, 0, len(" + expr + "))\n\t\tfor _, v := range " + expr + " {\n\t\t\tout = append(out, " + inner + ")\n\t\t}\n\n\t\treturn out\n\t}()", nil
}

func (e *emitter) mapToJSExpr(expr string, typed *types.Map, nonNil bool) (string, error) {
	key, err := mapKeyToString("k", typed.Key())
	if err != nil {
		return "", err
	}

	value, err := e.toJS("v", typed.Elem(), false)
	if err != nil {
		return "", err
	}

	empty := "nil"
	if nonNil {
		empty = "map[string]any{}"
	}

	return "func() any {\n\t\tif " + expr + " == nil {\n\t\t\treturn " + empty + "\n\t\t}\n\n\t\tout := make(map[string]any, len(" + expr + "))\n\t\tfor k, v := range " + expr + " {\n\t\t\tout[" + key + "] = " + value + "\n\t\t}\n\n\t\treturn out\n\t}()", nil
}

// mapKeyToString renders a map key as a JS property name without reaching for
// fmt, which would drag reflect back into the binary.
func mapKeyToString(expr string, t types.Type) (string, error) {
	basic, ok := t.Underlying().(*types.Basic)
	if !ok {
		return "", fmt.Errorf("map keys of type %s are not supported", t)
	}

	switch {
	case basic.Kind() == types.String:
		return "string(" + expr + ")", nil
	case basic.Info()&types.IsUnsigned != 0:
		return "strconv.FormatUint(uint64(" + expr + "), 10)", nil
	case basic.Info()&types.IsInteger != 0:
		return "strconv.FormatInt(int64(" + expr + "), 10)", nil
	case basic.Info()&types.IsFloat != 0:
		return "strconv.FormatFloat(float64(" + expr + "), 'g', -1, 64)", nil
	case basic.Kind() == types.Bool:
		return "strconv.FormatBool(bool(" + expr + "))", nil
	}

	return "", fmt.Errorf("map keys of type %s are not supported", t)
}

// fromJS renders a Go expression converting a js.Value into a Go value.
func (e *emitter) fromJS(expr string, t types.Type) (string, error) {
	if callback, ok := t.Underlying().(*types.Signature); ok {
		return e.callbackFromJS(expr, t, callback)
	}

	converter, err := e.ensureValueConverter(t)
	if err != nil {
		// The inner error already names the type, so restating it here would
		// only produce a message that says the same thing twice.
		return "", err
	}

	return "crystallineMust(" + converter + "(" + expr + "))", nil
}

// callbackFromJS renders a Go func that calls back into JS, awaiting whatever
// it returns so that an async callback behaves like a synchronous one.
func (e *emitter) callbackFromJS(expr string, t types.Type, sig *types.Signature) (string, error) {
	if sig.Results().Len() > 1 {
		return "", fmt.Errorf("callbacks returning %d values are not supported: JS returns one", sig.Results().Len())
	}

	params := make([]string, 0, sig.Params().Len())
	passed := make([]string, 0, sig.Params().Len())

	for i := 0; i < sig.Params().Len(); i++ {
		param := sig.Params().At(i)

		name := "p" + strconv.Itoa(i)

		params = append(params, name+" "+types.TypeString(param.Type(), e.qualifier))

		converted, err := e.toJS(name, param.Type(), false)
		if err != nil {
			return "", fmt.Errorf("callback parameter %d: %w", i+1, err)
		}

		passed = append(passed, converted)
	}

	invocation := "crystallineAwait(" + expr + ".Invoke(" + strings.Join(passed, ", ") + "))"

	var body strings.Builder

	body.WriteString("func(" + strings.Join(params, ", ") + ")")

	if sig.Results().Len() == 0 {
		body.WriteString(" {\n\t\t" + invocation + "\n\t}")

		return body.String(), nil
	}

	result := sig.Results().At(0).Type()

	converted, err := e.jsValueToGo("crystallineCallbackResult", result)
	if err != nil {
		return "", fmt.Errorf("callback result: %w", err)
	}

	body.WriteString(" " + types.TypeString(result, e.qualifier) + " {\n")
	body.WriteString("\t\tcrystallineCallbackResult := " + invocation + "\n\n")
	body.WriteString("\t\treturn " + converted + "\n")
	body.WriteString("\t}")

	return body.String(), nil
}

// fieldSetter renders the write half of a field accessor.
func (e *emitter) fieldSetter(target string, t types.Type) (string, error) {
	converted, err := e.jsValueToGo("value", t)
	if err != nil {
		return "", err
	}

	return "func(value js.Value) {\n\t\t" + target + " = " + converted + "\n\t}", nil
}

// emitConverter renders the JS to Go conversion for a struct: a wrapper handed
// back resolves to the value it came from, anything else is built field by
// field and validated.
func (e *emitter) emitStructConverter(fn string, named *types.Named) (string, error) {
	structType, ok := named.Underlying().(*types.Struct)
	if !ok {
		return "", fmt.Errorf("%s is not a struct", named.Obj().Name())
	}

	name := instantiatedName(named)
	goType := e.declaredName(named)

	var known []string

	var fields strings.Builder

	for i := 0; i < structType.NumFields(); i++ {
		field := structType.Field(i)
		if !field.Exported() {
			continue
		}

		known = append(known, strconv.Quote(field.Name())+": true")

		check, err := e.fieldFromJS("out."+field.Name(), name+"."+field.Name(), field.Type())
		if err != nil {
			return "", fmt.Errorf("%s.%s: %w", name, field.Name(), err)
		}

		fields.WriteString("\tif property := value.Get(" + strconv.Quote(field.Name()) + "); !property.IsUndefined() && !property.IsNull() {\n")
		fields.WriteString(check)
		fields.WriteString("\t}\n\n")
	}

	var body strings.Builder

	body.WriteString("var crystallineKnown" + name + " = map[string]bool{" + strings.Join(known, ", ") + "}\n\n")

	body.WriteString("func " + fn + "(value js.Value) (" + goType + ", error) {\n")
	body.WriteString("\tvar out " + goType + "\n\n")
	body.WriteString("\tif value.IsUndefined() || value.IsNull() {\n\t\treturn out, nil\n\t}\n\n")
	body.WriteString("\tif handle, ok := crystallineHandleOf(value); ok {\n")
	body.WriteString("\t\tresolved, found := crystallineResolve(handle)\n")
	body.WriteString("\t\tif !found {\n\t\t\treturn out, errors.New(" + strconv.Quote(name+": the value behind this handle has been released") + ")\n\t\t}\n\n")
	body.WriteString("\t\ttyped, ok := resolved.(*" + goType + ")\n")
	body.WriteString("\t\tif !ok {\n\t\t\treturn out, errors.New(" + strconv.Quote(name+": handle refers to a different type") + ")\n\t\t}\n\n")
	body.WriteString("\t\treturn *typed, nil\n\t}\n\n")
	body.WriteString("\tif value.Type() != js.TypeObject {\n\t\treturn out, errors.New(" + strconv.Quote(name+": expected an object") + ")\n\t}\n\n")
	body.WriteString("\tif err := crystallineUnknownProperty(value, " + strconv.Quote(name) + ", crystallineKnown" + name + "); err != nil {\n\t\treturn out, err\n\t}\n\n")
	body.WriteString(fields.String())
	body.WriteString("\treturn out, nil\n}\n\n")

	return body.String(), nil
}

// fieldFromJS renders the read and assignment for one field.
func (e *emitter) fieldFromJS(target string, label string, t types.Type) (string, error) {
	converter, err := e.ensureValueConverter(t)
	if err != nil {
		return "", err
	}

	var body strings.Builder

	body.WriteString("\t\tconverted, err := " + converter + "(property)\n")
	body.WriteString("\t\tif err != nil {\n")
	body.WriteString("\t\t\treturn out, errors.New(" + strconv.Quote(label+": ") + " + err.Error())\n")
	body.WriteString("\t\t}\n\n")
	body.WriteString("\t\t" + target + " = converted\n")

	return body.String(), nil
}

// typeKey renders a type as a Go identifier fragment, so each one gets exactly
// one generated converter.
func typeKey(t types.Type) (string, error) {
	switch typed := t.(type) {
	case *types.Basic:
		return strings.Title(typed.Name()), nil //nolint:staticcheck
	case *types.Named:
		return instantiatedName(typed), nil
	case *types.Alias:
		return typed.Obj().Name(), nil
	case *types.Pointer:
		inner, err := typeKey(typed.Elem())

		return "Ptr" + inner, err
	case *types.Slice:
		if basic, ok := typed.Elem().Underlying().(*types.Basic); ok && basic.Kind() == types.Uint8 {
			return "Bytes", nil
		}

		inner, err := typeKey(typed.Elem())

		return "SliceOf" + inner, err
	case *types.Array:
		inner, err := typeKey(typed.Elem())

		return "ArrayOf" + strconv.FormatInt(typed.Len(), 10) + inner, err
	case *types.Map:
		key, err := typeKey(typed.Key())
		if err != nil {
			return "", err
		}

		value, err := typeKey(typed.Elem())

		return "MapOf" + key + "To" + value, err
	}

	return "", fmt.Errorf("type %s cannot be read from JS", t)
}

// ensureValueConverter generates the JS to Go conversion for a type, once, and
// returns the name of the generated function.
func (e *emitter) ensureValueConverter(t types.Type) (string, error) {
	key, err := typeKey(t)
	if err != nil {
		return "", err
	}

	name := "crystallineTo" + key

	if _, done := e.converters[key]; done {
		return name, nil
	}

	// Reserve the name first so a self-referential type terminates.
	e.converters[key] = ""

	body, err := e.emitValueConverter(name, t)
	if err != nil {
		delete(e.converters, key)

		return "", err
	}

	e.converters[key] = body

	return name, nil
}

func (e *emitter) emitValueConverter(name string, t types.Type) (string, error) {
	goType := types.TypeString(t, e.qualifier)

	switch typed := t.(type) {
	case *types.Basic:
		return e.emitBasicConverter(name, goType, typed)
	case *types.Named, *types.Alias:
		if _, ok := t.Underlying().(*types.Struct); ok {
			return e.emitStructConverter(name, t.(*types.Named))
		}

		return e.emitValueConverterFor(name, goType, t.Underlying())
	case *types.Pointer:
		return e.emitPointerConverter(name, goType, typed)
	case *types.Slice:
		if basic, ok := typed.Elem().Underlying().(*types.Basic); ok && basic.Kind() == types.Uint8 {
			return emitBytesConverter(name, goType), nil
		}

		return e.emitSliceConverter(name, goType, typed)
	case *types.Array:
		return e.emitArrayConverter(name, goType, typed)
	case *types.Map:
		return e.emitMapConverter(name, goType, typed)
	}

	return "", fmt.Errorf("type %s cannot be read from JS", t)
}

// emitValueConverterFor handles a defined type by converting through its
// underlying type and casting.
func (e *emitter) emitValueConverterFor(name string, goType string, underlying types.Type) (string, error) {
	inner, err := e.ensureValueConverter(underlying)
	if err != nil {
		return "", err
	}

	return "func " + name + "(value js.Value) (" + goType + ", error) {\n" +
		"\tconverted, err := " + inner + "(value)\n" +
		"\tif err != nil {\n\t\tvar zero " + goType + "\n\n\t\treturn zero, err\n\t}\n\n" +
		"\treturn " + goType + "(converted), nil\n}\n\n", nil
}

func (e *emitter) emitBasicConverter(name string, goType string, basic *types.Basic) (string, error) {
	var expected, accessor string

	switch {
	case basic.Kind() == types.Bool:
		expected, accessor = "js.TypeBoolean", "value.Bool()"
	case basic.Kind() == types.String:
		expected, accessor = "js.TypeString", "value.String()"
	case basic.Info()&types.IsNumeric != 0:
		expected, accessor = "js.TypeNumber", "value.Float()"
	default:
		return "", fmt.Errorf("type %s cannot be read from JS", basic)
	}

	want := strings.ToLower(strings.TrimPrefix(expected, "js.Type"))

	return "func " + name + "(value js.Value) (" + goType + ", error) {\n" +
		"\tvar zero " + goType + "\n\n" +
		"\tif value.Type() != " + expected + " {\n\t\treturn zero, errors.New(" + strconv.Quote("expected a "+want) + ")\n\t}\n\n" +
		"\treturn " + goType + "(" + accessor + "), nil\n}\n\n", nil
}

func emitBytesConverter(name string, goType string) string {
	return "func " + name + "(value js.Value) (" + goType + ", error) {\n" +
		"\tif value.IsUndefined() || value.IsNull() {\n\t\treturn nil, nil\n\t}\n\n" +
		"\tif value.Get(\"byteLength\").Type() != js.TypeNumber {\n\t\treturn nil, errors.New(\"expected a Uint8Array\")\n\t}\n\n" +
		"\tout := make(" + goType + ", value.Get(\"length\").Int())\n" +
		"\tjs.CopyBytesToGo(out, value)\n\n" +
		"\treturn out, nil\n}\n\n"
}

func (e *emitter) emitSliceConverter(name string, goType string, typed *types.Slice) (string, error) {
	inner, err := e.ensureValueConverter(typed.Elem())
	if err != nil {
		return "", err
	}

	return "func " + name + "(value js.Value) (" + goType + ", error) {\n" +
		"\tif value.IsUndefined() || value.IsNull() {\n\t\treturn nil, nil\n\t}\n\n" +
		"\tif !js.Global().Get(\"Array\").Call(\"isArray\", value).Bool() {\n\t\treturn nil, errors.New(\"expected an array\")\n\t}\n\n" +
		"\tout := make(" + goType + ", 0, value.Length())\n\n" +
		"\tfor i := 0; i < value.Length(); i++ {\n" +
		"\t\titem, err := " + inner + "(value.Index(i))\n" +
		"\t\tif err != nil {\n\t\t\treturn nil, errors.New(\"[\" + strconv.Itoa(i) + \"]: \" + err.Error())\n\t\t}\n\n" +
		"\t\tout = append(out, item)\n\t}\n\n" +
		"\treturn out, nil\n}\n\n", nil
}

func (e *emitter) emitArrayConverter(name string, goType string, typed *types.Array) (string, error) {
	inner, err := e.ensureValueConverter(typed.Elem())
	if err != nil {
		return "", err
	}

	length := strconv.FormatInt(typed.Len(), 10)

	return "func " + name + "(value js.Value) (" + goType + ", error) {\n" +
		"\tvar out " + goType + "\n\n" +
		"\tif value.IsUndefined() || value.IsNull() {\n\t\treturn out, nil\n\t}\n\n" +
		"\tif !js.Global().Get(\"Array\").Call(\"isArray\", value).Bool() {\n\t\treturn out, errors.New(\"expected an array\")\n\t}\n\n" +
		"\tif value.Length() != " + length + " {\n\t\treturn out, errors.New(\"expected " + length + " items, got \" + strconv.Itoa(value.Length()))\n\t}\n\n" +
		"\tfor i := 0; i < " + length + "; i++ {\n" +
		"\t\titem, err := " + inner + "(value.Index(i))\n" +
		"\t\tif err != nil {\n\t\t\treturn out, errors.New(\"[\" + strconv.Itoa(i) + \"]: \" + err.Error())\n\t\t}\n\n" +
		"\t\tout[i] = item\n\t}\n\n" +
		"\treturn out, nil\n}\n\n", nil
}

func (e *emitter) emitMapConverter(name string, goType string, typed *types.Map) (string, error) {
	keyExpr, err := mapKeyFromString("key", typed.Key(), e.qualifier)
	if err != nil {
		return "", err
	}

	inner, err := e.ensureValueConverter(typed.Elem())
	if err != nil {
		return "", err
	}

	return "func " + name + "(value js.Value) (" + goType + ", error) {\n" +
		"\tif value.IsUndefined() || value.IsNull() {\n\t\treturn nil, nil\n\t}\n\n" +
		"\tif value.Type() != js.TypeObject {\n\t\treturn nil, errors.New(\"expected an object\")\n\t}\n\n" +
		"\tkeys := js.Global().Get(\"Object\").Call(\"keys\", value)\n" +
		"\tout := make(" + goType + ", keys.Length())\n\n" +
		"\tfor i := 0; i < keys.Length(); i++ {\n" +
		"\t\tkey := keys.Index(i).String()\n\n" +
		keyExpr +
		"\t\titem, err := " + inner + "(value.Get(key))\n" +
		"\t\tif err != nil {\n\t\t\treturn nil, errors.New(\"[\" + key + \"]: \" + err.Error())\n\t\t}\n\n" +
		"\t\tout[converted] = item\n\t}\n\n" +
		"\treturn out, nil\n}\n\n", nil
}

// mapKeyFromString parses a JS property name back into a Go map key.
func mapKeyFromString(expr string, t types.Type, qualifier types.Qualifier) (string, error) {
	basic, ok := t.Underlying().(*types.Basic)
	if !ok {
		return "", fmt.Errorf("map keys of type %s cannot be read from JS", t)
	}

	goType := types.TypeString(t, qualifier)

	switch {
	case basic.Kind() == types.String:
		return "\t\tconverted := " + goType + "(" + expr + ")\n\n", nil
	case basic.Info()&types.IsUnsigned != 0:
		return "\t\tparsed, err := strconv.ParseUint(" + expr + ", 10, 64)\n" +
			"\t\tif err != nil {\n\t\t\treturn nil, errors.New(\"key \" + " + expr + " + \" is not a number\")\n\t\t}\n\n" +
			"\t\tconverted := " + goType + "(parsed)\n\n", nil
	case basic.Info()&types.IsInteger != 0:
		return "\t\tparsed, err := strconv.ParseInt(" + expr + ", 10, 64)\n" +
			"\t\tif err != nil {\n\t\t\treturn nil, errors.New(\"key \" + " + expr + " + \" is not a number\")\n\t\t}\n\n" +
			"\t\tconverted := " + goType + "(parsed)\n\n", nil
	}

	return "", fmt.Errorf("map keys of type %s cannot be read from JS", t)
}

func (e *emitter) emitPointerConverter(name string, goType string, typed *types.Pointer) (string, error) {
	named, ok := typed.Elem().(*types.Named)
	if !ok || !isStructType(named) {
		return e.emitSimplePointerConverter(name, goType, typed)
	}

	inner, err := e.ensureValueConverter(named)
	if err != nil {
		return "", err
	}

	elem := types.TypeString(named, e.qualifier)

	// A wrapper resolves to the very pointer it was made from, so a round trip
	// through JS does not silently become a copy.
	return "func " + name + "(value js.Value) (" + goType + ", error) {\n" +
		"\tif value.IsUndefined() || value.IsNull() {\n\t\treturn nil, nil\n\t}\n\n" +
		"\tif handle, ok := crystallineHandleOf(value); ok {\n" +
		"\t\tresolved, found := crystallineResolve(handle)\n" +
		"\t\tif !found {\n\t\t\treturn nil, errors.New(\"the value behind this handle has been released\")\n\t\t}\n\n" +
		"\t\ttyped, ok := resolved.(*" + elem + ")\n" +
		"\t\tif !ok {\n\t\t\treturn nil, errors.New(\"handle refers to a different type\")\n\t\t}\n\n" +
		"\t\treturn typed, nil\n\t}\n\n" +
		"\tbuilt, err := " + inner + "(value)\n" +
		"\tif err != nil {\n\t\treturn nil, err\n\t}\n\n" +
		"\treturn &built, nil\n}\n\n", nil
}

// jsValueToGo converts an already-resolved js.Value into a Go value.
func (e *emitter) jsValueToGo(expr string, t types.Type) (string, error) {
	basic, ok := t.Underlying().(*types.Basic)
	if !ok {
		return "", fmt.Errorf("type %s is not supported", t)
	}

	name := types.TypeString(t, e.qualifier)

	switch {
	case basic.Kind() == types.Bool:
		return name + "(" + expr + ".Bool())", nil
	case basic.Kind() == types.String:
		return name + "(" + expr + ".String())", nil
	case basic.Info()&types.IsNumeric != 0:
		return name + "(" + expr + ".Float())", nil
	}

	return "", fmt.Errorf("type %s is not supported", t)
}

// qualifier renders a type as generated code must spell it.
func (e *emitter) qualifier(pkg *types.Package) string {
	return e.imports.qualifier(pkg)
}

func (e *emitter) isIgnored(named *types.Named, method string) bool {
	return e.marks.ignored[markKey(named, method)]
}

func (e *emitter) isPromised(named *types.Named, method string, obj types.Object) bool {
	return e.marks.promised[markKey(named, method)] || e.gen.isPromise(obj)
}

func (e *emitter) emitMarshaller(named *types.Named) (string, error) {
	structType, ok := named.Underlying().(*types.Struct)
	if !ok {
		return "", fmt.Errorf("%s is not a struct", named.Obj().Name())
	}

	name := instantiatedName(named)

	var body strings.Builder

	body.WriteString("func " + marshalName(name) + "(v *" + e.declaredName(named) + ") any {\n")
	body.WriteString("\tif v == nil {\n\t\treturn nil\n\t}\n\n")
	body.WriteString("\tout := js.Global().Get(\"Object\").New()\n")
	body.WriteString("\tscope := &crystallineScope{}\n\n")

	for i := 0; i < structType.NumFields(); i++ {
		field := structType.Field(i)
		if !field.Exported() {
			continue
		}

		tag := reflect.StructTag(structType.Tag(i)).Get(tagName)
		if err := validateTag(tag); err != nil {
			return "", fmt.Errorf("%s.%s: %w", name, field.Name(), err)
		}

		expr, err := e.toJS("v."+field.Name(), field.Type(), tagHasOption(tag, tagNotNil))
		if err != nil {
			e.skip(name+"."+field.Name(), err.Error())

			continue
		}

		setter, err := e.fieldSetter("v."+field.Name(), field.Type())
		if err != nil {
			// A field that cannot be written back is still readable.
			setter = "func(js.Value) {}"
		}

		body.WriteString("\tcrystallineDefine(scope, out, " + strconv.Quote(field.Name()) + ", func() any {\n\t\treturn " + expr + "\n\t}, " + setter + ")\n")
	}

	methods := make([]*types.Func, 0, named.NumMethods())
	for i := 0; i < named.NumMethods(); i++ {
		if method := named.Method(i); method.Exported() {
			methods = append(methods, method)
		}
	}

	sort.Slice(methods, func(i, j int) bool { return methods[i].Name() < methods[j].Name() })

	for _, method := range methods {
		if e.isIgnored(named, method.Name()) {
			continue
		}

		bound, err := e.emitMethod(named, method)
		if err != nil {
			e.skip(name+"."+method.Name(), err.Error())

			continue
		}

		body.WriteString("\tout.Set(" + strconv.Quote(method.Name()) + ", " + bound + ")\n")
	}

	body.WriteString("\n\tcrystallineAttach(out, crystallineRetain(v, scope), scope)\n\n")
	body.WriteString("\treturn out\n}\n\n")

	return body.String(), nil
}

func (e *emitter) emitMethod(named *types.Named, method *types.Func) (string, error) {
	sig := method.Type().(*types.Signature)

	call, preamble, err := e.emitArguments(sig)
	if err != nil {
		return "", err
	}

	returns, err := e.emitReturn("v."+method.Name()+"("+strings.Join(call, ", ")+")", sig.Results())
	returns = preamble + returns
	if err != nil {
		return "", err
	}

	var body strings.Builder

	body.WriteString("crystallineWrap(scope.fn(func(this js.Value, args []js.Value) (result any) {\n")
	body.WriteString("\t\tdefer crystallineRecover(&result)\n\n")
	body.WriteString("\t\tif len(args) != " + strconv.Itoa(sig.Params().Len()) + " {\n")
	body.WriteString("\t\t\treturn crystallineFail(" + strconv.Quote(method.Name()+": expected "+strconv.Itoa(sig.Params().Len())+" arguments, got ") + " + strconv.Itoa(len(args)))\n")
	body.WriteString("\t\t}\n\n")
	body.WriteString(wrapPromise(returns, e.isPromised(named, method.Name(), method) || hasCallback(sig) || takesContext(sig) || takesChannel(sig), 2))
	body.WriteString("\t}))")

	return body.String(), nil
}

func (e *emitter) queue(named *types.Named) {
	if _, done := e.marshallers[instantiatedName(named)]; done {
		return
	}

	e.pending = append(e.pending, named)
}

func isErrorType(t types.Type) bool {
	obj := namedObject(t)

	return obj != nil && obj.Pkg() == nil && obj.Name() == "error"
}

// prelude is the fixed support code every generated file carries. It is
// duplicated per package rather than imported so that generated bindings never
// depend on the reflect-based runtime.
const prelude = `// crystallineNamespace resolves globalThis.go.<app>.<pkg>, creating each level.
func crystallineNamespace(app string, pkg string) js.Value {
	global := js.Global()

	root := global.Get("go")
	if root.IsUndefined() {
		global.Set("go", map[string]any{})
		root = global.Get("go")
	}

	appNamespace := root.Get(app)
	if appNamespace.IsUndefined() {
		root.Set(app, map[string]any{})
		appNamespace = root.Get(app)
	}

	packageNamespace := appNamespace.Get(pkg)
	if packageNamespace.IsUndefined() {
		appNamespace.Set(pkg, map[string]any{})
		packageNamespace = appNamespace.Get(pkg)
	}

	return packageNamespace
}

// crystallineFail reports a failure through the slot the generated wrap()
// helper reads, matching the reflect runtime's contract.
func crystallineFail(message string) any {
	js.Global().Set("goInternalError", message)

	return nil
}

func crystallineBytes(data []byte) any {
	if data == nil {
		return nil
	}

	out := js.Global().Get("Uint8Array").New(len(data))
	js.CopyBytesToJS(out, data)

	return out
}

// crystallinePromise runs body on its own goroutine and hands JS a Promise, so
// a long Go call does not block the single JS thread. A panic rejects rather
// than escaping into the wasm bridge.
func crystallinePromise(body func() any) any {
	return js.Global().Get("Promise").New(js.FuncOf(func(this js.Value, args []js.Value) any {
		resolve := args[0]
		reject := args[1]

		go func() {
			defer func() {
				if recovered := recover(); recovered != nil {
					reject.Invoke(js.Global().Get("Error").New(crystallineRecovered(recovered)))
				}
			}()

			resolve.Invoke(body())
		}()

		return nil
	}))
}

// crystallineRecovered renders a recovered value without reaching for fmt,
// which would drag reflect back into the binary.
func crystallineRecovered(recovered any) string {
	switch typed := recovered.(type) {
	case string:
		return typed
	case error:
		return typed.Error()
	}

	return "panic"
}

// crystallineWrapper turns the error slot into a thrown JS Error. Go cannot
// raise a JS exception from inside a callback, so the throw has to happen on
// the JS side.
var crystallineWrapper js.Value

func crystallineWrap(fn js.Func) js.Value {
	if crystallineWrapper.IsUndefined() {
		crystallineWrapper = js.Global().Call("eval", ` + "`" + `(fn) => (...args) => {
			const result = fn(...args);
			if (globalThis.goInternalError) {
				const error = new Error(globalThis.goInternalError);
				globalThis.goInternalError = undefined;
				throw error;
			}
			return result;
		}` + "`" + `)
	}

	return crystallineWrapper.Invoke(fn)
}

// crystallineIterator turns a Go channel into a JS async iterable, which is the
// same idea spelled the other language's way.
//
// next is called once per iteration and reports the value plus whether the
// channel is still open.
func crystallineIterator(next func() (any, bool)) any {
	iterator := js.Global().Get("Object").New()

	iterator.Set("next", js.FuncOf(func(this js.Value, args []js.Value) any {
		return crystallinePromise(func() any {
			result := js.Global().Get("Object").New()

			value, ok := next()
			if !ok {
				result.Set("done", true)
				result.Set("value", nil)

				return result
			}

			result.Set("done", false)
			result.Set("value", value)

			return result
		})
	}))

	iterable := js.Global().Get("Object").New()

	// Symbol.asyncIterator cannot be reached through Value.Set, which only
	// takes string keys, so the wiring is done in JS.
	js.Global().Call("eval", ` + "`" + `(iterable, iterator) => {
		iterable[Symbol.asyncIterator] = () => iterator;
		return iterable;
	}` + "`" + `).Invoke(iterable, iterator)

	return iterable
}

// crystallineSource normalises anything iterable into a stepping function, so
// an array, a generator and an async generator all work the same way.
var crystallineSourceOf js.Value

func crystallineSource(source js.Value) js.Value {
	if crystallineSourceOf.IsUndefined() {
		crystallineSourceOf = js.Global().Call("eval", ` + "`" + `(source) => {
			const iterator = source[Symbol.asyncIterator]
				? source[Symbol.asyncIterator]()
				: source[Symbol.iterator]();

			return {
				next: () => Promise.resolve(iterator.next()),
				stop: () => { if (iterator.return) { iterator.return(); } },
			};
		}` + "`" + `)
	}

	return crystallineSourceOf.Invoke(source)
}

// crystallineFeed drains a JS iterable into a Go channel on its own goroutine.
//
// The returned stop function ends the feed and tells the iterator no more will
// be read, so abandoning the channel does not strand the goroutine.
func crystallineFeed[T any](source js.Value, convert func(js.Value) (T, error)) (<-chan T, func()) {
	out := make(chan T)
	done := make(chan struct{})

	if source.IsUndefined() || source.IsNull() {
		close(out)

		return out, func() {}
	}

	iterator := crystallineSource(source)

	go func() {
		defer close(out)

		for {
			step := crystallineAwait(iterator.Call("next"))
			if step.Get("done").Truthy() {
				return
			}

			value, err := convert(step.Get("value"))
			if err != nil {
				return
			}

			select {
			case out <- value:
			case <-done:
				return
			}
		}
	}()

	var once sync.Once

	return out, func() {
		once.Do(func() {
			close(done)
			iterator.Call("stop")
		})
	}
}

// crystallineContext bridges a JS AbortSignal to a Go context, so a call that
// would otherwise hold the single JS thread can be cancelled.
func crystallineContext(signal js.Value) (context.Context, func()) {
	ctx, cancel := context.WithCancel(context.Background())

	if signal.IsUndefined() || signal.IsNull() {
		return ctx, cancel
	}

	if signal.Get("aborted").Truthy() {
		cancel()

		return ctx, cancel
	}

	listener := js.FuncOf(func(this js.Value, args []js.Value) any {
		cancel()

		return nil
	})

	signal.Call("addEventListener", "abort", listener)

	return ctx, func() {
		signal.Call("removeEventListener", "abort", listener)
		listener.Release()
		cancel()
	}
}

// crystallineAwait resolves a thenable, so a Go caller can treat an async JS
// callback like a synchronous one. It blocks, which is safe only because a
// callback forces the enclosing call onto a goroutine.
// crystallineHandleKey names the hidden property carrying a wrapper's handle.
// It is non-enumerable, so Object.keys and JSON.stringify do not see it.
const crystallineHandleKey = "__crystallineHandle"

// Wrappers are backed by a handle table rather than by copying, so a value
// handed back to Go resolves to the object it came from. Entries are released
// when JS collects the wrapper.
// crystallineScope collects the js.Func values a wrapper owns. Each one holds a
// slot in the Go/JS bridge until it is released, so a wrapper that is never
// released leaks one per field and method.
type crystallineScope struct {
	funcs []js.Func
}

func (s *crystallineScope) fn(handler func(js.Value, []js.Value) any) js.Func {
	created := js.FuncOf(handler)
	s.funcs = append(s.funcs, created)

	return created
}

type crystallineEntry struct {
	value any
	scope *crystallineScope
}

var (
	crystallineHandleMutex sync.Mutex
	crystallineHandles     = make(map[int]crystallineEntry)
	crystallineHandleNext  int
	crystallineFinalizer   js.Value
)

func crystallineRetain(value any, scope *crystallineScope) int {
	crystallineHandleMutex.Lock()
	defer crystallineHandleMutex.Unlock()

	crystallineHandleNext++
	crystallineHandles[crystallineHandleNext] = crystallineEntry{value: value, scope: scope}

	return crystallineHandleNext
}

func crystallineResolve(handle int) (any, bool) {
	crystallineHandleMutex.Lock()
	defer crystallineHandleMutex.Unlock()

	entry, ok := crystallineHandles[handle]

	return entry.value, ok
}

// crystallineReleaseHandle drops a wrapper and frees the bridge slots it held.
func crystallineReleaseHandle(handle int) {
	crystallineHandleMutex.Lock()
	entry, ok := crystallineHandles[handle]
	delete(crystallineHandles, handle)
	crystallineHandleMutex.Unlock()

	if !ok || entry.scope == nil {
		return
	}

	for _, released := range entry.scope.funcs {
		released.Release()
	}

	entry.scope.funcs = nil
}

// crystallineAttach tags a wrapper with its handle and arranges for the entry
// to be dropped once JS no longer holds the wrapper.
func crystallineAttach(target js.Value, handle int, scope *crystallineScope) {
	js.Global().Get("Object").Call("defineProperty", target, crystallineHandleKey, map[string]any{
		"value":      handle,
		"enumerable": false,
	})

	// Explicit disposal, so a caller that knows when it is done need not wait
	// for the collector. Symbol.dispose cannot be reached through Value.Set,
	// which only takes string keys.
	disposer := scope.fn(func(this js.Value, args []js.Value) any {
		crystallineReleaseHandle(handle)

		return nil
	})

	target.Set("release", disposer)

	js.Global().Call("eval", ` + "`" + `(target, dispose) => {
		if (typeof Symbol.dispose !== "undefined") {
			target[Symbol.dispose] = dispose;
		}
	}` + "`" + `).Invoke(target, disposer)

	if crystallineFinalizer.IsUndefined() {
		constructor := js.Global().Get("FinalizationRegistry")
		if constructor.IsUndefined() {
			return
		}

		crystallineFinalizer = constructor.New(js.FuncOf(func(this js.Value, args []js.Value) any {
			if len(args) > 0 {
				crystallineReleaseHandle(args[0].Int())
			}

			return nil
		}))
	}

	crystallineFinalizer.Call("register", target, handle)
}

// crystallineHandleOf recovers the handle a wrapper carries, if any.
func crystallineHandleOf(value js.Value) (int, bool) {
	if value.Type() != js.TypeObject {
		return 0, false
	}

	handle := value.Get(crystallineHandleKey)
	if handle.Type() != js.TypeNumber {
		return 0, false
	}

	return handle.Int(), true
}

// crystallineUnknownProperty reports a property the target type does not have,
// so that a misspelling fails instead of silently leaving a zero value.
func crystallineUnknownProperty(value js.Value, typeName string, known map[string]bool) error {
	keys := js.Global().Get("Object").Call("keys", value)

	for i := 0; i < keys.Length(); i++ {
		name := keys.Index(i).String()
		if !known[name] {
			return errors.New(typeName + ": unknown property " + strconv.Quote(name))
		}
	}

	return nil
}

func crystallineAwait(value js.Value) js.Value {
	if value.Type() != js.TypeObject || value.Get("then").Type() != js.TypeFunction {
		return value
	}

	settled := make(chan js.Value, 1)
	failed := make(chan string, 1)

	onResolved := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) == 0 {
			settled <- js.Undefined()
		} else {
			settled <- args[0]
		}

		return nil
	})
	defer onResolved.Release()

	onRejected := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) == 0 {
			failed <- "promise rejected"
		} else {
			failed <- args[0].String()
		}

		return nil
	})
	defer onRejected.Release()

	value.Call("then", onResolved, onRejected)

	select {
	case result := <-settled:
		return result
	case message := <-failed:
		panic(message)
	}
}

// crystallineDefine installs accessors so that reads and writes from JS reach
// the Go value, rather than operating on a detached copy.
func crystallineDefine(scope *crystallineScope, target js.Value, name string, get func() any, set func(js.Value)) {
	js.Global().Get("Object").Call("defineProperty", target, name, map[string]any{
		"enumerable": true,
		"get": scope.fn(func(this js.Value, args []js.Value) any {
			return get()
		}),
		"set": scope.fn(func(this js.Value, args []js.Value) any {
			if len(args) > 0 {
				set(args[0])
			}

			return nil
		}),
	})
}

// crystallineRecover turns a panic into a reported failure, so a bad argument
// surfaces as a thrown Error rather than tearing down the wasm runtime.
func crystallineRecover(result *any) {
	if recovered := recover(); recovered != nil {
		*result = crystallineFail(crystallineRecovered(recovered))
	}
}

// crystallineMust unwraps a conversion, turning a failure into a panic that the
// wrapper's recover reports back to JS as a thrown Error.
func crystallineMust[T any](value T, err error) T {
	if err != nil {
		panic(err.Error())
	}

	return value
}

// crystallineOk and crystallineErr build the Result a fallible call returns.
// Failure travels in the value, so a call that can fail need not be async.
// crystallineResultProto carries the Result methods. They live on a prototype
// built once rather than on each result: attaching js.Func values per call
// would allocate a bridge slot for every fallible call and leak it.
var crystallineResultProto js.Value

func crystallineResultPrototype() js.Value {
	if crystallineResultProto.IsUndefined() {
		crystallineResultProto = js.Global().Call("eval", ` + "`" + `({
			unwrap() {
				if (this.ok) {
					return this.value;
				}
				throw this.error;
			},
			unwrapOr(fallback) {
				return this.ok ? this.value : fallback;
			},
		})` + "`" + `)
	}

	return crystallineResultProto
}

func crystallineOk(value any) any {
	out := js.Global().Get("Object").Call("create", crystallineResultPrototype())
	out.Set("ok", true)
	out.Set("value", value)

	return out
}

func crystallineErr(err error) any {
	out := js.Global().Get("Object").Call("create", crystallineResultPrototype())
	out.Set("ok", false)
	out.Set("error", js.Global().Get("Error").New(err.Error()))

	return out
}

func crystallineError(err error) any {
	if err == nil {
		return nil
	}

	return js.Global().Get("Error").New(err.Error())
}

`

// contextPackage is the import path of the only package whose type is given a
// meaning of its own.
const contextPackage = "context"

func isStructType(named *types.Named) bool {
	_, ok := named.Underlying().(*types.Struct)

	return ok
}

// emitSimplePointerConverter handles a pointer to something that is not a
// struct, where there is no handle to recover and null simply means absent.
func (e *emitter) emitSimplePointerConverter(name string, goType string, typed *types.Pointer) (string, error) {
	inner, err := e.ensureValueConverter(typed.Elem())
	if err != nil {
		return "", err
	}

	return "func " + name + "(value js.Value) (" + goType + ", error) {\n" +
		"\tif value.IsUndefined() || value.IsNull() {\n\t\treturn nil, nil\n\t}\n\n" +
		"\tconverted, err := " + inner + "(value)\n" +
		"\tif err != nil {\n\t\treturn nil, err\n\t}\n\n" +
		"\treturn &converted, nil\n}\n\n", nil
}
