//go:build js

// Code generated by crystalline. DO NOT EDIT.

package main

import (
	"context"
	"errors"
	"strconv"
	"sync"
	"syscall/js"

	bind "github.com/Vilsol/crystalline/bind"
	account "github.com/Vilsol/crystalline/examples/02-accounts/account"
)

func init() {
	crystallineNamespace("accounts", "account").Set("Open", crystallineWrap(js.FuncOf(crystallineFnAccountOpen)))
	crystallineNamespace("accounts", "account").Set("Transfer", crystallineWrap(js.FuncOf(crystallineFnAccountTransfer)))
	crystallineNamespace("accounts", "account").Set("Summarise", crystallineWrap(js.FuncOf(crystallineFnAccountSummarise)))
	crystallineNamespace("accounts", "account").Set("ParseAmount", crystallineWrap(js.FuncOf(crystallineFnAccountParseAmount)))

	Exports(crystallineRegistry{})
}

// crystallineRegistry receives what the manifests declare. Everything but a
// value is already bound above, so the rest are no-ops.
type crystallineRegistry struct{}

func (crystallineRegistry) Func(fn any, opts ...bind.Option) {}

func (crystallineRegistry) Plain(zero any) {}

func (crystallineRegistry) Type(zero any) {}

func (crystallineRegistry) Ignore(zero any, method string) {}

func (crystallineRegistry) Promise(zero any, method string) {}

func (crystallineRegistry) Value(name string, value any, opts ...bind.Option) {
}

// crystallineNamespace resolves globalThis.go.<app>.<pkg>, creating each level.
func crystallineNamespace(app string, pkg string) js.Value {
	global := js.Global()

	root := global.Get("go")
	if root.IsUndefined() {
		global.Set("go", map[string]any{})
		root = global.Get("go")
	}

	appNamespace := root.Get(app)
	if appNamespace.IsUndefined() {
		root.Set(app, map[string]any{})
		appNamespace = root.Get(app)
	}

	packageNamespace := appNamespace.Get(pkg)
	if packageNamespace.IsUndefined() {
		appNamespace.Set(pkg, map[string]any{})
		packageNamespace = appNamespace.Get(pkg)
	}

	return packageNamespace
}

// crystallineFail reports a failure through the slot the generated wrap()
// helper reads, matching the reflect runtime's contract.
func crystallineFail(message string) any {
	js.Global().Set("goInternalError", message)

	return nil
}

func crystallineBytes(data []byte) any {
	if data == nil {
		return nil
	}

	out := js.Global().Get("Uint8Array").New(len(data))
	js.CopyBytesToJS(out, data)

	return out
}

// crystallinePromise runs body on its own goroutine and hands JS a Promise, so
// a long Go call does not block the single JS thread. A panic rejects rather
// than escaping into the wasm bridge.
func crystallinePromise(body func() any) any {
	return js.Global().Get("Promise").New(js.FuncOf(func(this js.Value, args []js.Value) any {
		resolve := args[0]
		reject := args[1]

		go func() {
			defer func() {
				if recovered := recover(); recovered != nil {
					reject.Invoke(js.Global().Get("Error").New(crystallineRecovered(recovered)))
				}
			}()

			resolve.Invoke(body())
		}()

		return nil
	}))
}

// crystallineRecovered renders a recovered value without reaching for fmt,
// which would drag reflect back into the binary.
func crystallineRecovered(recovered any) string {
	switch typed := recovered.(type) {
	case string:
		return typed
	case error:
		return typed.Error()
	}

	return "panic"
}

// crystallineWrapper turns the error slot into a thrown JS Error. Go cannot
// raise a JS exception from inside a callback, so the throw has to happen on
// the JS side.
var crystallineWrapper js.Value

func crystallineWrap(fn js.Func) js.Value {
	if crystallineWrapper.IsUndefined() {
		crystallineWrapper = js.Global().Call("eval", `(fn) => (...args) => {
			const result = fn(...args);
			if (globalThis.goInternalError) {
				const error = new Error(globalThis.goInternalError);
				globalThis.goInternalError = undefined;
				throw error;
			}
			return result;
		}`)
	}

	return crystallineWrapper.Invoke(fn)
}

// crystallineIterator turns a Go channel into a JS async iterable, which is the
// same idea spelled the other language's way.
//
// next is called once per iteration and reports the value plus whether the
// channel is still open. stop tears down whatever governs the stream, and runs
// once the stream ends however it ends.
func crystallineIterator(next func() (any, bool), stop func()) any {
	var once sync.Once

	finish := func() {
		once.Do(stop)
	}

	iterator := js.Global().Get("Object").New()

	iterator.Set("next", js.FuncOf(func(this js.Value, args []js.Value) any {
		return crystallinePromise(func() any {
			result := js.Global().Get("Object").New()

			value, ok := next()
			if !ok {
				finish()

				result.Set("done", true)
				result.Set("value", nil)

				return result
			}

			result.Set("done", false)
			result.Set("value", value)

			return result
		})
	}))

	// A consumer that stops early -- breaking out of a for await -- asks the
	// iterator to return. That is the only notice Go gets that nobody is
	// reading any more, so it is where an abandoned stream is torn down.
	iterator.Set("return", js.FuncOf(func(this js.Value, args []js.Value) any {
		finish()

		result := js.Global().Get("Object").New()
		result.Set("done", true)
		result.Set("value", nil)

		return result
	}))

	iterable := js.Global().Get("Object").New()

	// Symbol.asyncIterator cannot be reached through Value.Set, which only
	// takes string keys, so the wiring is done in JS.
	js.Global().Call("eval", `(iterable, iterator) => {
		iterable[Symbol.asyncIterator] = () => iterator;
		return iterable;
	}`).Invoke(iterable, iterator)

	return iterable
}

// crystallineSource normalises anything iterable into a stepping function, so
// an array, a generator and an async generator all work the same way.
var crystallineSourceOf js.Value

func crystallineSource(source js.Value) js.Value {
	if crystallineSourceOf.IsUndefined() {
		crystallineSourceOf = js.Global().Call("eval", `(source) => {
			const iterator = source[Symbol.asyncIterator]
				? source[Symbol.asyncIterator]()
				: source[Symbol.iterator]();

			return {
				next: () => Promise.resolve(iterator.next()),
				stop: () => { if (iterator.return) { iterator.return(); } },
			};
		}`)
	}

	return crystallineSourceOf.Invoke(source)
}

// crystallineFeed drains a JS iterable into a Go channel on its own goroutine.
//
// The returned stop function ends the feed and tells the iterator no more will
// be read, so abandoning the channel does not strand the goroutine.
func crystallineFeed[T any](source js.Value, convert func(js.Value) (T, error)) (<-chan T, func()) {
	out := make(chan T)
	done := make(chan struct{})

	if source.IsUndefined() || source.IsNull() {
		close(out)

		return out, func() {}
	}

	iterator := crystallineSource(source)

	go func() {
		defer close(out)

		for {
			step := crystallineAwait(iterator.Call("next"))
			if step.Get("done").Truthy() {
				return
			}

			value, err := convert(step.Get("value"))
			if err != nil {
				return
			}

			select {
			case out <- value:
			case <-done:
				return
			}
		}
	}()

	var once sync.Once

	return out, func() {
		once.Do(func() {
			close(done)
			iterator.Call("stop")
		})
	}
}

// crystallineContext bridges a JS AbortSignal to a Go context, so a call that
// would otherwise hold the single JS thread can be cancelled.
func crystallineContext(signal js.Value) (context.Context, func()) {
	ctx, cancel := context.WithCancel(context.Background())

	if signal.IsUndefined() || signal.IsNull() {
		return ctx, cancel
	}

	if signal.Get("aborted").Truthy() {
		cancel()

		return ctx, cancel
	}

	listener := js.FuncOf(func(this js.Value, args []js.Value) any {
		cancel()

		return nil
	})

	signal.Call("addEventListener", "abort", listener)

	return ctx, func() {
		signal.Call("removeEventListener", "abort", listener)
		listener.Release()
		cancel()
	}
}

// crystallineAwait resolves a thenable, so a Go caller can treat an async JS
// callback like a synchronous one. It blocks, which is safe only because a
// callback forces the enclosing call onto a goroutine.
// crystallineHandleKey names the hidden property carrying a wrapper's handle.
// It is non-enumerable, so Object.keys and JSON.stringify do not see it.
const crystallineHandleKey = "__crystallineHandle"

// Wrappers are backed by a handle table rather than by copying, so a value
// handed back to Go resolves to the object it came from. Entries are released
// when JS collects the wrapper.
// crystallineScope collects the js.Func values a wrapper owns. Each one holds a
// slot in the Go/JS bridge until it is released, so a wrapper that is never
// released leaks one per field and method.
type crystallineScope struct {
	funcs []js.Func
}

func (s *crystallineScope) fn(handler func(js.Value, []js.Value) any) js.Func {
	created := js.FuncOf(handler)
	s.funcs = append(s.funcs, created)

	return created
}

type crystallineEntry struct {
	value any
	scope *crystallineScope
}

var (
	crystallineHandleMutex sync.Mutex
	crystallineHandles     = make(map[int]crystallineEntry)
	crystallineHandleNext  int
	crystallineFinalizer   js.Value
)

func crystallineRetain(value any, scope *crystallineScope) int {
	crystallineHandleMutex.Lock()
	defer crystallineHandleMutex.Unlock()

	crystallineHandleNext++
	crystallineHandles[crystallineHandleNext] = crystallineEntry{value: value, scope: scope}

	return crystallineHandleNext
}

func crystallineResolve(handle int) (any, bool) {
	crystallineHandleMutex.Lock()
	defer crystallineHandleMutex.Unlock()

	entry, ok := crystallineHandles[handle]

	return entry.value, ok
}

// crystallineReleaseHandle drops a wrapper and frees the bridge slots it held.
func crystallineReleaseHandle(handle int) {
	crystallineHandleMutex.Lock()
	entry, ok := crystallineHandles[handle]
	delete(crystallineHandles, handle)
	crystallineHandleMutex.Unlock()

	if !ok || entry.scope == nil {
		return
	}

	for _, released := range entry.scope.funcs {
		released.Release()
	}

	entry.scope.funcs = nil
}

// crystallineAttach tags a wrapper with its handle and arranges for the entry
// to be dropped once JS no longer holds the wrapper.
func crystallineAttach(target js.Value, handle int, scope *crystallineScope) {
	js.Global().Get("Object").Call("defineProperty", target, crystallineHandleKey, map[string]any{
		"value":      handle,
		"enumerable": false,
	})

	// Explicit disposal, so a caller that knows when it is done need not wait
	// for the collector. Symbol.dispose cannot be reached through Value.Set,
	// which only takes string keys.
	disposer := scope.fn(func(this js.Value, args []js.Value) any {
		crystallineReleaseHandle(handle)

		return nil
	})

	target.Set("release", disposer)

	js.Global().Call("eval", `(target, dispose) => {
		if (typeof Symbol.dispose !== "undefined") {
			target[Symbol.dispose] = dispose;
		}
	}`).Invoke(target, disposer)

	if crystallineFinalizer.IsUndefined() {
		constructor := js.Global().Get("FinalizationRegistry")
		if constructor.IsUndefined() {
			return
		}

		crystallineFinalizer = constructor.New(js.FuncOf(func(this js.Value, args []js.Value) any {
			if len(args) > 0 {
				crystallineReleaseHandle(args[0].Int())
			}

			return nil
		}))
	}

	crystallineFinalizer.Call("register", target, handle)
}

// crystallineHandleOf recovers the handle a wrapper carries, if any.
func crystallineHandleOf(value js.Value) (int, bool) {
	if value.Type() != js.TypeObject {
		return 0, false
	}

	handle := value.Get(crystallineHandleKey)
	if handle.Type() != js.TypeNumber {
		return 0, false
	}

	return handle.Int(), true
}

// crystallineUnknownProperty reports a property the target type does not have,
// so that a misspelling fails instead of silently leaving a zero value.
func crystallineUnknownProperty(value js.Value, typeName string, known map[string]bool) error {
	keys := js.Global().Get("Object").Call("keys", value)

	for i := 0; i < keys.Length(); i++ {
		name := keys.Index(i).String()
		if !known[name] {
			return errors.New(typeName + ": unknown property " + strconv.Quote(name))
		}
	}

	return nil
}

func crystallineAwait(value js.Value) js.Value {
	if value.Type() != js.TypeObject || value.Get("then").Type() != js.TypeFunction {
		return value
	}

	settled := make(chan js.Value, 1)
	failed := make(chan string, 1)

	onResolved := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) == 0 {
			settled <- js.Undefined()
		} else {
			settled <- args[0]
		}

		return nil
	})
	defer onResolved.Release()

	onRejected := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) == 0 {
			failed <- "promise rejected"
		} else {
			failed <- args[0].String()
		}

		return nil
	})
	defer onRejected.Release()

	value.Call("then", onResolved, onRejected)

	select {
	case result := <-settled:
		return result
	case message := <-failed:
		panic(message)
	}
}

// crystallineDefine installs accessors so that reads and writes from JS reach
// the Go value, rather than operating on a detached copy.
func crystallineDefine(scope *crystallineScope, target js.Value, name string, get func() any, set func(js.Value)) {
	js.Global().Get("Object").Call("defineProperty", target, name, map[string]any{
		"enumerable": true,
		"get": scope.fn(func(this js.Value, args []js.Value) any {
			return get()
		}),
		// Wrapped, because a write now validates: handing a string to a number
		// field has to throw where the write happened rather than poison the
		// next unrelated call.
		"set": crystallineWrap(scope.fn(func(this js.Value, args []js.Value) (result any) {
			defer crystallineRecover(&result)

			if len(args) > 0 {
				set(args[0])
			}

			return nil
		})),
	})
}

// crystallineRecover turns a panic into a reported failure, so a bad argument
// surfaces as a thrown Error rather than tearing down the wasm runtime.
func crystallineRecover(result *any) {
	if recovered := recover(); recovered != nil {
		*result = crystallineFail(crystallineRecovered(recovered))
	}
}

// crystallineMust unwraps a conversion, turning a failure into a panic that the
// wrapper's recover reports back to JS as a thrown Error.
func crystallineMust[T any](value T, err error) T {
	if err != nil {
		panic(err.Error())
	}

	return value
}

// crystallineOk and crystallineErr build the Result a fallible call returns.
// Failure travels in the value, so a call that can fail need not be async.
// crystallineResultProto carries the Result methods. They live on a prototype
// built once rather than on each result: attaching js.Func values per call
// would allocate a bridge slot for every fallible call and leak it.
var crystallineResultProto js.Value

func crystallineResultPrototype() js.Value {
	if crystallineResultProto.IsUndefined() {
		crystallineResultProto = js.Global().Call("eval", `({
			unwrap() {
				if (this.ok) {
					return this.value;
				}
				throw this.error;
			},
			unwrapOr(fallback) {
				return this.ok ? this.value : fallback;
			},
		})`)
	}

	return crystallineResultProto
}

func crystallineOk(value any) any {
	out := js.Global().Get("Object").Call("create", crystallineResultPrototype())
	out.Set("ok", true)
	out.Set("value", value)

	return out
}

func crystallineErr(err error) any {
	out := js.Global().Get("Object").Call("create", crystallineResultPrototype())
	out.Set("ok", false)
	out.Set("error", js.Global().Get("Error").New(err.Error()))

	return out
}

func crystallineError(err error) any {
	if err == nil {
		return nil
	}

	return js.Global().Get("Error").New(err.Error())
}

func crystallineFnAccountOpen(this js.Value, args []js.Value) (result any) {
	defer crystallineRecover(&result)

	if len(args) != 2 {
		return crystallineFail("Open: expected 2 arguments, got " + strconv.Itoa(len(args)))
	}

	r0 := account.Open(crystallineMust(crystallineToString(args[0])), crystallineMust(crystallineToInt(args[1])))

	return crystallineMarshalAccount(r0)
}

func crystallineFnAccountTransfer(this js.Value, args []js.Value) (result any) {
	defer crystallineRecover(&result)

	if len(args) != 3 {
		return crystallineFail("Transfer: expected 3 arguments, got " + strconv.Itoa(len(args)))
	}

	r0 := account.Transfer(crystallineMust(crystallineToPtrAccount(args[0])), crystallineMust(crystallineToPtrAccount(args[1])), crystallineMust(crystallineToInt(args[2])))

	if r0 != nil {
		return crystallineErr(r0)
	}

	return crystallineOk(nil)
}

func crystallineFnAccountSummarise(this js.Value, args []js.Value) (result any) {
	defer crystallineRecover(&result)

	if len(args) != 1 {
		return crystallineFail("Summarise: expected 1 arguments, got " + strconv.Itoa(len(args)))
	}

	r0 := account.Summarise(crystallineMust(crystallineToAccount(args[0])))

	return string(r0)
}

func crystallineFnAccountParseAmount(this js.Value, args []js.Value) (result any) {
	defer crystallineRecover(&result)

	if len(args) != 1 {
		return crystallineFail("ParseAmount: expected 1 arguments, got " + strconv.Itoa(len(args)))
	}

	r0, r1 := account.ParseAmount(crystallineMust(crystallineToString(args[0])))

	if r1 != nil {
		return crystallineErr(r1)
	}

	return crystallineOk(float64(r0))
}

func crystallineMarshalAccount(v *account.Account) any {
	if v == nil {
		return nil
	}

	out := js.Global().Get("Object").New()
	scope := &crystallineScope{}

	crystallineDefine(scope, out, "Owner", func() any {
		return string(v.Owner)
	}, func(value js.Value) {
		v.Owner = crystallineMust(crystallineToString(value))
	})
	crystallineDefine(scope, out, "Balance", func() any {
		return float64(v.Balance)
	}, func(value js.Value) {
		v.Balance = crystallineMust(crystallineToInt(value))
	})
	crystallineDefine(scope, out, "History", func() any {
		return func() any {
			if v.History == nil {
				return []any{}
			}

			out := make([]any, 0, len(v.History))
			for _, v := range v.History {
				out = append(out, string(v))
			}

			return out
		}()
	}, func(value js.Value) {
		v.History = crystallineMust(crystallineToSliceOfString(value))
	})
	out.Set("Deposit", crystallineWrap(scope.fn(func(this js.Value, args []js.Value) (result any) {
		defer crystallineRecover(&result)

		if len(args) != 1 {
			return crystallineFail("Deposit: expected 1 arguments, got " + strconv.Itoa(len(args)))
		}

		r0 := v.Deposit(crystallineMust(crystallineToInt(args[0])))

		if r0 != nil {
			return crystallineErr(r0)
		}

		return crystallineOk(nil)
	})))
	out.Set("Snapshot", crystallineWrap(scope.fn(func(this js.Value, args []js.Value) (result any) {
		defer crystallineRecover(&result)

		if len(args) != 0 {
			return crystallineFail("Snapshot: expected 0 arguments, got " + strconv.Itoa(len(args)))
		}

		r0 := v.Snapshot()

		return crystallineMarshalStatement(&r0)
	})))
	out.Set("Statement", crystallineWrap(scope.fn(func(this js.Value, args []js.Value) (result any) {
		defer crystallineRecover(&result)

		if len(args) != 0 {
			return crystallineFail("Statement: expected 0 arguments, got " + strconv.Itoa(len(args)))
		}

		r0 := v.Statement()

		return string(r0)
	})))
	out.Set("Withdraw", crystallineWrap(scope.fn(func(this js.Value, args []js.Value) (result any) {
		defer crystallineRecover(&result)

		if len(args) != 1 {
			return crystallineFail("Withdraw: expected 1 arguments, got " + strconv.Itoa(len(args)))
		}

		r0 := v.Withdraw(crystallineMust(crystallineToInt(args[0])))

		if r0 != nil {
			return crystallineErr(r0)
		}

		return crystallineOk(nil)
	})))

	crystallineAttach(out, crystallineRetain(v, scope), scope)

	return out
}

func crystallineMarshalStatement(v *account.Statement) any {
	if v == nil {
		return nil
	}

	out := js.Global().Get("Object").New()

	out.Set("Owner", string(v.Owner))
	out.Set("Balance", float64(v.Balance))
	out.Set("Entries", func() any {
		if v.Entries == nil {
			return nil
		}

		out := make([]any, 0, len(v.Entries))
		for _, v := range v.Entries {
			out = append(out, string(v))
		}

		return out
	}())

	return out
}

var crystallineKnownAccount = map[string]bool{"Owner": true, "Balance": true, "History": true}

func crystallineToAccount(value js.Value) (account.Account, error) {
	var out account.Account

	if value.IsUndefined() || value.IsNull() {
		return out, errors.New("Account: expected an object, got null")
	}

	if handle, ok := crystallineHandleOf(value); ok {
		resolved, found := crystallineResolve(handle)
		if !found {
			return out, errors.New("Account: the value behind this handle has been released")
		}

		typed, ok := resolved.(*account.Account)
		if !ok {
			return out, errors.New("Account: handle refers to a different type")
		}

		return *typed, nil
	}

	if value.Type() != js.TypeObject {
		return out, errors.New("Account: expected an object")
	}

	if err := crystallineUnknownProperty(value, "Account", crystallineKnownAccount); err != nil {
		return out, err
	}

	if property := value.Get("Owner"); !property.IsUndefined() && !property.IsNull() {
		converted, err := crystallineToString(property)
		if err != nil {
			return out, errors.New("Account.Owner: " + err.Error())
		}

		out.Owner = converted
	}

	if property := value.Get("Balance"); !property.IsUndefined() && !property.IsNull() {
		converted, err := crystallineToInt(property)
		if err != nil {
			return out, errors.New("Account.Balance: " + err.Error())
		}

		out.Balance = converted
	}

	if property := value.Get("History"); !property.IsUndefined() && !property.IsNull() {
		converted, err := crystallineToSliceOfString(property)
		if err != nil {
			return out, errors.New("Account.History: " + err.Error())
		}

		out.History = converted
	}

	return out, nil
}

func crystallineToInt(value js.Value) (int, error) {
	var zero int

	if value.Type() != js.TypeNumber {
		return zero, errors.New("expected a number")
	}

	return int(value.Float()), nil
}

func crystallineToPtrAccount(value js.Value) (*account.Account, error) {
	if value.IsUndefined() || value.IsNull() {
		return nil, nil
	}

	if handle, ok := crystallineHandleOf(value); ok {
		resolved, found := crystallineResolve(handle)
		if !found {
			return nil, errors.New("the value behind this handle has been released")
		}

		typed, ok := resolved.(*account.Account)
		if !ok {
			return nil, errors.New("handle refers to a different type")
		}

		return typed, nil
	}

	built, err := crystallineToAccount(value)
	if err != nil {
		return nil, err
	}

	return &built, nil
}

func crystallineToSliceOfString(value js.Value) ([]string, error) {
	if value.IsUndefined() || value.IsNull() {
		return nil, nil
	}

	if !js.Global().Get("Array").Call("isArray", value).Bool() {
		return nil, errors.New("expected an array")
	}

	out := make([]string, 0, value.Length())

	for i := 0; i < value.Length(); i++ {
		item, err := crystallineToString(value.Index(i))
		if err != nil {
			return nil, errors.New("[" + strconv.Itoa(i) + "]: " + err.Error())
		}

		out = append(out, item)
	}

	return out, nil
}

func crystallineToString(value js.Value) (string, error) {
	var zero string

	if value.Type() != js.TypeString {
		return zero, errors.New("expected a string")
	}

	return string(value.String()), nil
}
