//go:build js

// Code generated by crystalline. DO NOT EDIT.

package main

import (
	"context"
	"errors"
	"strconv"
	"sync"
	"syscall/js"

	bind "github.com/Vilsol/crystalline/bind"
	catalogue "github.com/Vilsol/crystalline/examples/04-catalogue/catalogue"
	time "time"
)

func init() {
	crystallineNamespace("catalogue", "catalogue").Set("All", crystallineWrap(js.FuncOf(crystallineFnCatalogueAll)))
	crystallineNamespace("catalogue", "catalogue").Set("Describe", crystallineWrap(js.FuncOf(crystallineFnCatalogueDescribe)))
	crystallineNamespace("catalogue", "catalogue").Set("Restock", crystallineWrap(js.FuncOf(crystallineFnCatalogueRestock)))
	crystallineNamespace("catalogue", "catalogue").Set("Status", map[string]any{
		"StatusDraft":     float64(0),
		"StatusPublished": float64(1),
		"StatusArchived":  float64(2),
	})

	Exports(crystallineRegistry{})
}

// crystallineRegistry receives what the manifests declare. Everything but a
// value is already bound above, so the rest are no-ops.
//
// The interface is embedded so that a method added to it later does not stop
// this file compiling before it has been regenerated.
type crystallineRegistry struct{ bind.Registry }

func (crystallineRegistry) Func(fn any, opts ...bind.Option) {}

func (crystallineRegistry) Type(zero any, opts ...bind.Option) {}

func (crystallineRegistry) Value(name string, value any, opts ...bind.Option) {
}

// crystallineNamespace resolves globalThis.go.<app>.<pkg>, creating each level.
func crystallineNamespace(app string, pkg string) js.Value {
	global := js.Global()

	root := global.Get("go")
	if root.IsUndefined() {
		global.Set("go", map[string]any{})
		root = global.Get("go")
	}

	appNamespace := root.Get(app)
	if appNamespace.IsUndefined() {
		root.Set(app, map[string]any{})
		appNamespace = root.Get(app)
	}

	packageNamespace := appNamespace.Get(pkg)
	if packageNamespace.IsUndefined() {
		appNamespace.Set(pkg, map[string]any{})
		packageNamespace = appNamespace.Get(pkg)
	}

	return packageNamespace
}

// crystallineFail reports a failure through the slot the generated wrap()
// helper reads, matching the reflect runtime's contract.
func crystallineFail(message string) any {
	js.Global().Set("goInternalError", message)

	return nil
}

func crystallineBytes(data []byte) any {
	if data == nil {
		return nil
	}

	out := js.Global().Get("Uint8Array").New(len(data))
	js.CopyBytesToJS(out, data)

	return out
}

// crystallinePromise runs body on its own goroutine and hands JS a Promise, so
// a long Go call does not block the single JS thread. A panic rejects rather
// than escaping into the wasm bridge.
func crystallinePromise(body func() any) any {
	executor := js.FuncOf(func(this js.Value, args []js.Value) any {
		resolve := args[0]
		reject := args[1]

		go func() {
			defer func() {
				if recovered := recover(); recovered != nil {
					reject.Invoke(js.Global().Get("Error").New(crystallineRecovered(recovered)))
				}
			}()

			value := body()

			// A failure inside the body travels through the same slot a
			// synchronous call uses, so generated code has one way to report
			// one and needs no panic to do it. The JS wrapper cannot read the
			// slot here: it handed back the promise before the body ran.
			if failure := js.Global().Get("goInternalError"); !failure.IsUndefined() {
				js.Global().Set("goInternalError", js.Undefined())
				reject.Invoke(js.Global().Get("Error").New(failure.String()))

				return
			}

			resolve.Invoke(value)
		}()

		return nil
	})

	promise := js.Global().Get("Promise").New(executor)

	// The Promise constructor calls the executor synchronously and never again,
	// so its slot in the Go/JS bridge goes back now. Held, it leaked one slot
	// per promise-returning call for the life of the page.
	executor.Release()

	return promise
}

// crystallineRecovered renders a recovered value without reaching for fmt,
// which would drag reflect back into the binary.
func crystallineRecovered(recovered any) string {
	switch typed := recovered.(type) {
	case string:
		return typed
	case error:
		return typed.Error()
	}

	return "panic"
}

// crystallineWrapper turns the error slot into a thrown JS Error. Go cannot
// raise a JS exception from inside a callback, so the throw has to happen on
// the JS side.
var crystallineWrapper js.Value

func crystallineWrap(fn js.Func) js.Value {
	if crystallineWrapper.IsUndefined() {
		crystallineWrapper = js.Global().Call("eval", `(fn) => (...args) => {
			const result = fn(...args);
			if (globalThis.goInternalError) {
				const error = new Error(globalThis.goInternalError);
				globalThis.goInternalError = undefined;
				throw error;
			}
			return result;
		}`)
	}

	return crystallineWrapper.Invoke(fn)
}

// crystallineIterator turns a Go channel into a JS async iterable, which is the
// same idea spelled the other language's way.
//
// next is called once per iteration and reports the value plus whether the
// channel is still open. stop tears down whatever governs the stream, and runs
// once the stream ends however it ends.
func crystallineIterator(next func() (any, bool), stop func()) any {
	var once sync.Once

	finish := func() {
		once.Do(stop)
	}

	iterator := js.Global().Get("Object").New()

	iterator.Set("next", js.FuncOf(func(this js.Value, args []js.Value) any {
		return crystallinePromise(func() any {
			result := js.Global().Get("Object").New()

			value, ok := next()
			if !ok {
				finish()

				result.Set("done", true)
				result.Set("value", nil)

				return result
			}

			result.Set("done", false)
			result.Set("value", value)

			return result
		})
	}))

	// A consumer that stops early -- breaking out of a for await -- asks the
	// iterator to return. That is the only notice Go gets that nobody is
	// reading any more, so it is where an abandoned stream is torn down.
	iterator.Set("return", js.FuncOf(func(this js.Value, args []js.Value) any {
		finish()

		result := js.Global().Get("Object").New()
		result.Set("done", true)
		result.Set("value", nil)

		return result
	}))

	iterable := js.Global().Get("Object").New()

	// Symbol.asyncIterator cannot be reached through Value.Set, which only
	// takes string keys, so the wiring is done in JS.
	js.Global().Call("eval", `(iterable, iterator) => {
		iterable[Symbol.asyncIterator] = () => iterator;
		return iterable;
	}`).Invoke(iterable, iterator)

	return iterable
}

// crystallineSource normalises anything iterable into a stepping function, so
// an array, a generator and an async generator all work the same way.
var crystallineSourceOf js.Value

func crystallineSource(source js.Value) js.Value {
	if crystallineSourceOf.IsUndefined() {
		crystallineSourceOf = js.Global().Call("eval", `(source) => {
			const iterator = source[Symbol.asyncIterator]
				? source[Symbol.asyncIterator]()
				: source[Symbol.iterator]();

			return {
				next: () => Promise.resolve(iterator.next()),
				stop: () => { if (iterator.return) { iterator.return(); } },
			};
		}`)
	}

	return crystallineSourceOf.Invoke(source)
}

// crystallineFeed drains a JS iterable into a Go channel on its own goroutine.
//
// The returned stop function ends the feed and tells the iterator no more will
// be read, so abandoning the channel does not strand the goroutine.
func crystallineFeed[T any](source js.Value, convert func(js.Value) (T, error)) (<-chan T, func() error) {
	out := make(chan T)
	done := make(chan struct{})
	finished := make(chan struct{})

	if source.IsUndefined() || source.IsNull() {
		close(out)

		return out, func() error { return nil }
	}

	iterator := crystallineSource(source)

	// failure is written before finished is closed and read after, so the close
	// orders the two.
	var failure error

	go func() {
		defer close(finished)
		defer close(out)

		for {
			step, err := crystallineAwaited(iterator.Call("next"))
			if err != nil {
				// A rejecting source used to panic here, in a goroutine with
				// no recover, which ends the program rather than the call.
				failure = err

				return
			}

			if step.Get("done").Truthy() {
				return
			}

			value, err := convert(step.Get("value"))
			if err != nil {
				// Ending the stream here would look like a clean end of input,
				// and Go would answer for the values that did arrive.
				failure = err

				return
			}

			select {
			case out <- value:
			case <-done:
				return
			}
		}
	}()

	var once sync.Once

	// Idempotent, and reports whatever ended the feed. The wrapper calls it
	// after the Go function returns and fails the call if the input was bad.
	return out, func() error {
		once.Do(func() {
			close(done)
			iterator.Call("stop")
		})

		<-finished

		return failure
	}
}

// crystallineContext bridges a JS AbortSignal to a Go context, so a call that
// would otherwise hold the single JS thread can be cancelled.
func crystallineContext(signal js.Value) (context.Context, func()) {
	ctx, cancel := context.WithCancel(context.Background())

	if signal.IsUndefined() || signal.IsNull() {
		return ctx, cancel
	}

	if signal.Get("aborted").Truthy() {
		cancel()

		return ctx, cancel
	}

	listener := js.FuncOf(func(this js.Value, args []js.Value) any {
		cancel()

		return nil
	})

	signal.Call("addEventListener", "abort", listener)

	return ctx, func() {
		signal.Call("removeEventListener", "abort", listener)
		listener.Release()
		cancel()
	}
}

// crystallineAwait resolves a thenable, so a Go caller can treat an async JS
// callback like a synchronous one. It blocks, which is safe only because a
// callback forces the enclosing call onto a goroutine.
// crystallineHandleKey names the hidden property carrying a wrapper's handle.
// It is non-enumerable, so Object.keys and JSON.stringify do not see it.
const crystallineHandleKey = "__crystallineHandle"

// Wrappers are backed by a handle table rather than by copying, so a value
// handed back to Go resolves to the object it came from. Entries are released
// when JS collects the wrapper.
// crystallineScope collects the js.Func values a wrapper owns. Each one holds a
// slot in the Go/JS bridge until it is released, so a wrapper that is never
// released leaks one per field and method.
type crystallineScope struct {
	funcs []js.Func
}

func (s *crystallineScope) fn(handler func(js.Value, []js.Value) any) js.Func {
	created := js.FuncOf(handler)
	s.funcs = append(s.funcs, created)

	return created
}

type crystallineEntry struct {
	value any
	scope *crystallineScope
}

var (
	crystallineHandleMutex sync.Mutex
	crystallineHandles     = make(map[int]crystallineEntry)
	crystallineHandleNext  int
	crystallineFinalizer   js.Value
)

func crystallineRetain(value any, scope *crystallineScope) int {
	crystallineHandleMutex.Lock()
	defer crystallineHandleMutex.Unlock()

	crystallineHandleNext++
	crystallineHandles[crystallineHandleNext] = crystallineEntry{value: value, scope: scope}

	return crystallineHandleNext
}

func crystallineResolve(handle int) (any, bool) {
	crystallineHandleMutex.Lock()
	defer crystallineHandleMutex.Unlock()

	entry, ok := crystallineHandles[handle]

	return entry.value, ok
}

// crystallineReleaseHandle drops a wrapper and frees the bridge slots it held.
func crystallineReleaseHandle(handle int) {
	crystallineHandleMutex.Lock()
	entry, ok := crystallineHandles[handle]
	delete(crystallineHandles, handle)
	crystallineHandleMutex.Unlock()

	if !ok || entry.scope == nil {
		return
	}

	for _, released := range entry.scope.funcs {
		released.Release()
	}

	entry.scope.funcs = nil
}

// crystallineAttach tags a wrapper with its handle and arranges for the entry
// to be dropped once JS no longer holds the wrapper.
func crystallineAttach(target js.Value, handle int, scope *crystallineScope) {
	js.Global().Get("Object").Call("defineProperty", target, crystallineHandleKey, map[string]any{
		"value":      handle,
		"enumerable": false,
	})

	// Explicit disposal, so a caller that knows when it is done need not wait
	// for the collector. Symbol.dispose cannot be reached through Value.Set,
	// which only takes string keys.
	disposer := scope.fn(func(this js.Value, args []js.Value) any {
		crystallineReleaseHandle(handle)

		return nil
	})

	target.Set("release", disposer)

	js.Global().Call("eval", `(target, dispose) => {
		if (typeof Symbol.dispose !== "undefined") {
			target[Symbol.dispose] = dispose;
		}
	}`).Invoke(target, disposer)

	if crystallineFinalizer.IsUndefined() {
		constructor := js.Global().Get("FinalizationRegistry")
		if constructor.IsUndefined() {
			return
		}

		crystallineFinalizer = constructor.New(js.FuncOf(func(this js.Value, args []js.Value) any {
			if len(args) > 0 {
				crystallineReleaseHandle(args[0].Int())
			}

			return nil
		}))
	}

	crystallineFinalizer.Call("register", target, handle)
}

// crystallineHandleOf recovers the handle a wrapper carries, if any.
func crystallineHandleOf(value js.Value) (int, bool) {
	if value.Type() != js.TypeObject {
		return 0, false
	}

	handle := value.Get(crystallineHandleKey)
	if handle.Type() != js.TypeNumber {
		return 0, false
	}

	return handle.Int(), true
}

// crystallineUnknownProperty reports a property the target type does not have,
// so that a misspelling fails instead of silently leaving a zero value.
func crystallineUnknownProperty(value js.Value, typeName string, known map[string]bool) error {
	keys := js.Global().Get("Object").Call("keys", value)

	for i := 0; i < keys.Length(); i++ {
		name := keys.Index(i).String()
		if !known[name] {
			return errors.New(typeName + ": unknown property " + strconv.Quote(name))
		}
	}

	return nil
}

// crystallineAwait resolves a thenable and panics if it rejects, which is the
// only answer in a function whose Go signature belongs to the consumer.
func crystallineAwait(value js.Value) js.Value {
	resolved, err := crystallineAwaited(value)
	if err != nil {
		panic(err.Error())
	}

	return resolved
}

// crystallineAwaited is the same wait for a caller that has somewhere to report
// a rejection to. A feed does: it already carries whatever ended it.
func crystallineAwaited(value js.Value) (js.Value, error) {
	if value.Type() != js.TypeObject || value.Get("then").Type() != js.TypeFunction {
		return value, nil
	}

	settled := make(chan js.Value, 1)
	failed := make(chan string, 1)

	onResolved := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) == 0 {
			settled <- js.Undefined()
		} else {
			settled <- args[0]
		}

		return nil
	})
	defer onResolved.Release()

	onRejected := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) == 0 {
			failed <- "promise rejected"
		} else {
			failed <- crystallineErrorText(args[0])
		}

		return nil
	})
	defer onRejected.Release()

	value.Call("then", onResolved, onRejected)

	select {
	case result := <-settled:
		return result, nil
	case message := <-failed:
		return js.Undefined(), errors.New(message)
	}
}

// crystallineErrorText renders whatever a promise rejected with. Value.String()
// on an Error object gives the literal "<object>", which names nothing, and
// that is what a rejection almost always carries.
func crystallineErrorText(value js.Value) string {
	if value.Type() == js.TypeObject {
		if message := value.Get("message"); message.Type() == js.TypeString {
			return message.String()
		}
	}

	return value.String()
}

// crystallineDefine installs accessors so that reads and writes from JS reach
// the Go value, rather than operating on a detached copy.
func crystallineDefine(scope *crystallineScope, target js.Value, name string, get func() any, set func(js.Value)) {
	js.Global().Get("Object").Call("defineProperty", target, name, map[string]any{
		"enumerable": true,
		"get": scope.fn(func(this js.Value, args []js.Value) any {
			return get()
		}),
		// Wrapped, because a write now validates: handing a string to a number
		// field has to throw where the write happened rather than poison the
		// next unrelated call.
		"set": crystallineWrap(scope.fn(func(this js.Value, args []js.Value) (result any) {
			defer crystallineRecover(&result)

			if len(args) > 0 {
				set(args[0])
			}

			return nil
		})),
	})
}

// crystallineRecover turns a panic into a reported failure, so a bad argument
// surfaces as a thrown Error rather than tearing down the wasm runtime.
func crystallineRecover(result *any) {
	if recovered := recover(); recovered != nil {
		*result = crystallineFail(crystallineRecovered(recovered))
	}
}

// crystallineBigInt and crystallineBigUint hand a 64-bit integer over as a
// JavaScript BigInt, which carries it exactly where a number cannot.
func crystallineBigInt(value int64) any {
	return js.Global().Get("BigInt").Invoke(strconv.FormatInt(value, 10))
}

func crystallineBigUint(value uint64) any {
	return js.Global().Get("BigInt").Invoke(strconv.FormatUint(value, 10))
}

// crystallineBigIntText reads the digits of a JavaScript BigInt, and reports
// whether it was one.
//
// Nothing here may look at the value through syscall/js. Value.Type panics with
// "bad type flag" on a BigInt — there is no type constant for one — and Get and
// Call check the type first, so even asking what it is crashes. JavaScript is
// asked instead, through calls that only pass the reference along.
func crystallineBigIntText(value js.Value) (string, bool) {
	tag := js.Global().Get("Object").Get("prototype").Get("toString").Call("call", value)
	if tag.String() != "[object BigInt]" {
		return "", false
	}

	return js.Global().Get("String").Invoke(value).String(), true
}

func crystallineToBigInt(value js.Value) (int64, error) {
	text, ok := crystallineBigIntText(value)
	if !ok {
		return 0, errors.New("expected a bigint")
	}

	parsed, err := strconv.ParseInt(text, 10, 64)
	if err != nil {
		return 0, errors.New(text + " does not fit in an int64")
	}

	return parsed, nil
}

func crystallineToBigUint(value js.Value) (uint64, error) {
	text, ok := crystallineBigIntText(value)
	if !ok {
		return 0, errors.New("expected a bigint")
	}

	parsed, err := strconv.ParseUint(text, 10, 64)
	if err != nil {
		return 0, errors.New(text + " does not fit in a uint64")
	}

	return parsed, nil
}

// crystallineMust unwraps a conversion, turning a failure into a panic that the
// wrapper's recover reports back to JS as a thrown Error.
func crystallineMust[T any](value T, err error) T {
	if err != nil {
		panic(err.Error())
	}

	return value
}

// crystallineOk and crystallineErr build the Result a fallible call returns.
// Failure travels in the value, so a call that can fail need not be async.
// crystallineResultProto carries the Result methods. They live on a prototype
// built once rather than on each result: attaching js.Func values per call
// would allocate a bridge slot for every fallible call and leak it.
var crystallineResultProto js.Value

func crystallineResultPrototype() js.Value {
	if crystallineResultProto.IsUndefined() {
		crystallineResultProto = js.Global().Call("eval", `({
			unwrap() {
				if (this.ok) {
					return this.value;
				}
				throw this.error;
			},
			unwrapOr(fallback) {
				return this.ok ? this.value : fallback;
			},
		})`)
	}

	return crystallineResultProto
}

func crystallineOk(value any) any {
	out := js.Global().Get("Object").Call("create", crystallineResultPrototype())
	out.Set("ok", true)
	out.Set("value", value)

	return out
}

func crystallineErr(err error) any {
	out := js.Global().Get("Object").Call("create", crystallineResultPrototype())
	out.Set("ok", false)
	out.Set("error", js.Global().Get("Error").New(err.Error()))

	return out
}

func crystallineError(err error) any {
	if err == nil {
		return nil
	}

	return js.Global().Get("Error").New(err.Error())
}

func crystallineFnCatalogueAll(this js.Value, args []js.Value) (result any) {
	defer crystallineRecover(&result)

	if len(args) != 0 {
		return crystallineFail("All: expected 0 arguments, got " + strconv.Itoa(len(args)))
	}

	r0 := catalogue.All()

	return func() any {
		if r0 == nil {
			return nil
		}

		out := make([]any, 0, len(r0))
		for _, v := range r0 {
			out = append(out, crystallineMarshalCatalogueItem(v))
		}

		return out
	}()
}

func crystallineFnCatalogueDescribe(this js.Value, args []js.Value) (result any) {
	defer crystallineRecover(&result)

	if len(args) != 1 {
		return crystallineFail("Describe: expected 1 arguments, got " + strconv.Itoa(len(args)))
	}

	a0, err := crystallineToPtrCatalogueItem(args[0])
	if err != nil {
		return crystallineFail(err.Error())
	}

	r0 := catalogue.Describe(a0)

	return string(r0)
}

func crystallineFnCatalogueRestock(this js.Value, args []js.Value) (result any) {
	defer crystallineRecover(&result)

	if len(args) != 2 {
		return crystallineFail("Restock: expected 2 arguments, got " + strconv.Itoa(len(args)))
	}

	return crystallinePromise(func() any {
		a0, err := crystallineToCatalogueNotifier(args[0])
		if err != nil {
			return crystallineFail(err.Error())
		}

		a1, err := crystallineToSliceOfString(args[1])
		if err != nil {
			return crystallineFail(err.Error())
		}

		r0 := catalogue.Restock(a0, a1)

		return float64(r0)
	})
}

func crystallineMarshalCatalogueAudited(v *catalogue.Audited) any {
	if v == nil {
		return nil
	}

	out := js.Global().Get("Object").New()
	scope := &crystallineScope{}

	var crystallineCacheCreatedAt any
	var crystallineCachedCreatedAt bool

	crystallineDefine(scope, out, "CreatedAt", func() any {
		if !crystallineCachedCreatedAt {
			crystallineCachedCreatedAt = true
			crystallineCacheCreatedAt = js.Global().Get("Date").New(float64(v.CreatedAt.UnixMilli()))
		}

		return crystallineCacheCreatedAt
	}, func(value js.Value) {
		converted, err := crystallineToTimeTime(value)
		if err != nil {
			crystallineFail(err.Error())

			return
		}

		v.CreatedAt = converted
	})
	out.Set("Listed", crystallineWrap(scope.fn(func(this js.Value, args []js.Value) (result any) {
		defer crystallineRecover(&result)

		if len(args) != 0 {
			return crystallineFail("Listed: expected 0 arguments, got " + strconv.Itoa(len(args)))
		}

		r0 := v.Listed()

		return string(r0)
	})))

	crystallineAttach(out, crystallineRetain(v, scope), scope)

	return out
}

func crystallineMarshalCatalogueItem(v *catalogue.Item) any {
	if v == nil {
		return nil
	}

	out := js.Global().Get("Object").New()
	scope := &crystallineScope{}

	var crystallineCacheAudited any
	var crystallineCachedAudited bool

	crystallineDefine(scope, out, "Audited", func() any {
		if !crystallineCachedAudited {
			crystallineCachedAudited = true
			crystallineCacheAudited = crystallineMarshalCatalogueAudited(&v.Audited)
		}

		return crystallineCacheAudited
	}, func(value js.Value) {
		converted, err := crystallineToCatalogueAudited(value)
		if err != nil {
			crystallineFail(err.Error())

			return
		}

		v.Audited = converted
	})
	crystallineDefine(scope, out, "Name", func() any {
		return string(v.Name)
	}, func(value js.Value) {
		converted, err := crystallineToString(value)
		if err != nil {
			crystallineFail(err.Error())

			return
		}

		v.Name = converted
	})
	var crystallineCachePrice any
	var crystallineCachedPrice bool

	crystallineDefine(scope, out, "Price", func() any {
		if !crystallineCachedPrice {
			crystallineCachedPrice = true
			crystallineCachePrice = string(catalogue.MoneyToText(v.Price))
		}

		return crystallineCachePrice
	}, func(value js.Value) {
		converted, err := crystallineToCatalogueMoney(value)
		if err != nil {
			crystallineFail(err.Error())

			return
		}

		v.Price = converted
	})
	crystallineDefine(scope, out, "Status", func() any {
		return float64(v.Status)
	}, func(value js.Value) {
		converted, err := crystallineToCatalogueStatus(value)
		if err != nil {
			crystallineFail(err.Error())

			return
		}

		v.Status = converted
	})
	out.Set("Listed", crystallineWrap(scope.fn(func(this js.Value, args []js.Value) (result any) {
		defer crystallineRecover(&result)

		if len(args) != 0 {
			return crystallineFail("Listed: expected 0 arguments, got " + strconv.Itoa(len(args)))
		}

		r0 := v.Listed()

		return string(r0)
	})))
	out.Set("Reprice", crystallineWrap(scope.fn(func(this js.Value, args []js.Value) (result any) {
		defer crystallineRecover(&result)

		if len(args) != 1 {
			return crystallineFail("Reprice: expected 1 arguments, got " + strconv.Itoa(len(args)))
		}

		a0, err := crystallineToCatalogueMoney(args[0])
		if err != nil {
			return crystallineFail(err.Error())
		}

		v.Reprice(a0)

		return nil
	})))

	crystallineAttach(out, crystallineRetain(v, scope), scope)

	return out
}

var crystallineKnownCatalogueAudited = map[string]bool{"CreatedAt": true}

func crystallineToCatalogueAudited(value js.Value) (catalogue.Audited, error) {
	var out catalogue.Audited

	if value.IsUndefined() || value.IsNull() {
		return out, errors.New("CatalogueAudited: expected an object, got null")
	}

	if handle, ok := crystallineHandleOf(value); ok {
		resolved, found := crystallineResolve(handle)
		if !found {
			return out, errors.New("CatalogueAudited: the value behind this handle has been released")
		}

		typed, ok := resolved.(*catalogue.Audited)
		if !ok {
			return out, errors.New("CatalogueAudited: handle refers to a different type")
		}

		return *typed, nil
	}

	if value.Type() != js.TypeObject {
		return out, errors.New("CatalogueAudited: expected an object")
	}

	if err := crystallineUnknownProperty(value, "CatalogueAudited", crystallineKnownCatalogueAudited); err != nil {
		return out, err
	}

	if property := value.Get("CreatedAt"); !property.IsUndefined() && !property.IsNull() {
		converted, err := crystallineToTimeTime(property)
		if err != nil {
			return out, errors.New("CatalogueAudited.CreatedAt: " + err.Error())
		}

		out.CreatedAt = converted
	}

	return out, nil
}

var crystallineKnownCatalogueItem = map[string]bool{"Audited": true, "Name": true, "Price": true, "Status": true}

func crystallineToCatalogueItem(value js.Value) (catalogue.Item, error) {
	var out catalogue.Item

	if value.IsUndefined() || value.IsNull() {
		return out, errors.New("CatalogueItem: expected an object, got null")
	}

	if handle, ok := crystallineHandleOf(value); ok {
		resolved, found := crystallineResolve(handle)
		if !found {
			return out, errors.New("CatalogueItem: the value behind this handle has been released")
		}

		typed, ok := resolved.(*catalogue.Item)
		if !ok {
			return out, errors.New("CatalogueItem: handle refers to a different type")
		}

		return *typed, nil
	}

	if value.Type() != js.TypeObject {
		return out, errors.New("CatalogueItem: expected an object")
	}

	if err := crystallineUnknownProperty(value, "CatalogueItem", crystallineKnownCatalogueItem); err != nil {
		return out, err
	}

	if property := value.Get("Audited"); !property.IsUndefined() && !property.IsNull() {
		converted, err := crystallineToCatalogueAudited(property)
		if err != nil {
			return out, errors.New("CatalogueItem.Audited: " + err.Error())
		}

		out.Audited = converted
	}

	if property := value.Get("Name"); !property.IsUndefined() && !property.IsNull() {
		converted, err := crystallineToString(property)
		if err != nil {
			return out, errors.New("CatalogueItem.Name: " + err.Error())
		}

		out.Name = converted
	}

	if property := value.Get("Price"); !property.IsUndefined() && !property.IsNull() {
		converted, err := crystallineToCatalogueMoney(property)
		if err != nil {
			return out, errors.New("CatalogueItem.Price: " + err.Error())
		}

		out.Price = converted
	}

	if property := value.Get("Status"); !property.IsUndefined() && !property.IsNull() {
		converted, err := crystallineToCatalogueStatus(property)
		if err != nil {
			return out, errors.New("CatalogueItem.Status: " + err.Error())
		}

		out.Status = converted
	}

	return out, nil
}

func crystallineToCatalogueMoney(value js.Value) (catalogue.Money, error) {
	crystallineCrossed, err := crystallineToString(value)
	if err != nil {
		var zero catalogue.Money

		return zero, err
	}

	return catalogue.MoneyFromText(crystallineCrossed)
}

type crystallineJSNotifier struct{ value js.Value }

func (c crystallineJSNotifier) Notify(p0 string) {
	crystallineAwait(c.value.Call("Notify", string(p0)))
}

func crystallineToCatalogueNotifier(value js.Value) (catalogue.Notifier, error) {
	if value.Type() != js.TypeObject {
		return nil, errors.New("Notifier: expected an object")
	}

	if value.Get("Notify").Type() != js.TypeFunction {
		return nil, errors.New("Notifier: the object has no Notify method")
	}

	return crystallineJSNotifier{value: value}, nil
}

func crystallineToCatalogueStatus(value js.Value) (catalogue.Status, error) {
	converted, err := crystallineToInt(value)
	if err != nil {
		var zero catalogue.Status

		return zero, err
	}

	return catalogue.Status(converted), nil
}

func crystallineToInt(value js.Value) (int, error) {
	var zero int

	if value.Type() != js.TypeNumber {
		return zero, errors.New("expected a number")
	}

	return int(value.Float()), nil
}

func crystallineToPtrCatalogueItem(value js.Value) (*catalogue.Item, error) {
	if value.IsUndefined() || value.IsNull() {
		return nil, nil
	}

	if handle, ok := crystallineHandleOf(value); ok {
		resolved, found := crystallineResolve(handle)
		if !found {
			return nil, errors.New("the value behind this handle has been released")
		}

		typed, ok := resolved.(*catalogue.Item)
		if !ok {
			return nil, errors.New("handle refers to a different type")
		}

		return typed, nil
	}

	built, err := crystallineToCatalogueItem(value)
	if err != nil {
		return nil, err
	}

	return &built, nil
}

func crystallineToSliceOfString(value js.Value) ([]string, error) {
	if value.IsUndefined() || value.IsNull() {
		return nil, nil
	}

	if !js.Global().Get("Array").Call("isArray", value).Bool() {
		return nil, errors.New("expected an array")
	}

	out := make([]string, 0, value.Length())

	for i := 0; i < value.Length(); i++ {
		item, err := crystallineToString(value.Index(i))
		if err != nil {
			return nil, errors.New("[" + strconv.Itoa(i) + "]: " + err.Error())
		}

		out = append(out, item)
	}

	return out, nil
}

func crystallineToString(value js.Value) (string, error) {
	var zero string

	if value.Type() != js.TypeString {
		return zero, errors.New("expected a string")
	}

	return string(value.String()), nil
}

func crystallineToTimeTime(value js.Value) (time.Time, error) {
	if !value.InstanceOf(js.Global().Get("Date")) {
		return time.Time{}, errors.New("expected a Date")
	}

	return time.UnixMilli(int64(value.Call("getTime").Float())).UTC(), nil
}
