//go:build js

// Code generated by crystalline. DO NOT EDIT.

package main

import (
	"context"
	"errors"
	"strconv"
	"sync"
	"syscall/js"

	bind "github.com/Vilsol/crystalline/bind"
	ledger "github.com/Vilsol/crystalline/examples/05-ledger/ledger"
)

func init() {
	if crystallineImported, err := crystallineResolvePath("localStorage"); err != nil {
		crystallineImportFailed("ledger.Saved", err)
	} else if crystallineFilled, err := crystallineImportLedgerStore(crystallineImported); err != nil {
		crystallineImportFailed("ledger.Saved", err)
	} else {
		ledger.Saved = crystallineFilled
	}

	crystallinePublishImportFailures("ledger")

	crystallineNamespace("ledger", "ledger").Set("add", crystallineWrap(js.FuncOf(crystallineFnLedgerAdd)))
	crystallineNamespace("ledger", "ledger").Set("balance", crystallineWrap(js.FuncOf(crystallineFnLedgerBalance)))
	crystallineNamespace("ledger", "ledger").Set("forget", crystallineWrap(js.FuncOf(crystallineFnLedgerForget)))

	Exports(crystallineRegistry{})
}

// crystallineRegistry receives what the manifests declare. Everything but a
// value is already bound above, so the rest are no-ops.
//
// The interface is embedded so that a method added to it later does not stop
// this file compiling before it has been regenerated.
type crystallineRegistry struct{ bind.Registry }

func (crystallineRegistry) Func(fn any, opts ...bind.Option) {}

func (crystallineRegistry) Type(zero any, opts ...bind.Option) {}

func (crystallineRegistry) Import(target any, opts ...bind.Option) {}

func (crystallineRegistry) Value(name string, value any, opts ...bind.Option) {
}

// crystallineNamespace resolves globalThis.go.<app>.<pkg>, creating each level.
func crystallineNamespace(app string, pkg string) js.Value {
	global := js.Global()

	root := global.Get("go")
	if root.IsUndefined() {
		global.Set("go", map[string]any{})
		root = global.Get("go")
	}

	appNamespace := root.Get(app)
	if appNamespace.IsUndefined() {
		root.Set(app, map[string]any{})
		appNamespace = root.Get(app)
	}

	packageNamespace := appNamespace.Get(pkg)
	if packageNamespace.IsUndefined() {
		appNamespace.Set(pkg, map[string]any{})
		packageNamespace = appNamespace.Get(pkg)
	}

	return packageNamespace
}

// crystallineFail reports a failure through the slot the generated wrap()
// helper reads, matching the reflect runtime's contract.
func crystallineFail(message string) any {
	js.Global().Set("goInternalError", message)

	return nil
}

func crystallineBytes(data []byte) any {
	if data == nil {
		return nil
	}

	out := js.Global().Get("Uint8Array").New(len(data))
	js.CopyBytesToJS(out, data)

	return out
}

// crystallinePromise runs body on its own goroutine and hands JS a Promise, so
// a long Go call does not block the single JS thread. A panic rejects rather
// than escaping into the wasm bridge.
func crystallinePromise(body func() any) any {
	executor := js.FuncOf(func(this js.Value, args []js.Value) any {
		resolve := args[0]
		reject := args[1]

		go func() {
			defer func() {
				if recovered := recover(); recovered != nil {
					reject.Invoke(js.Global().Get("Error").New(crystallineRecovered(recovered)))
				}
			}()

			value := body()

			// A failure inside the body travels through the same slot a
			// synchronous call uses, so generated code has one way to report
			// one and needs no panic to do it. The JS wrapper cannot read the
			// slot here: it handed back the promise before the body ran.
			if failure := js.Global().Get("goInternalError"); !failure.IsUndefined() {
				js.Global().Set("goInternalError", js.Undefined())
				reject.Invoke(js.Global().Get("Error").New(failure.String()))

				return
			}

			resolve.Invoke(value)
		}()

		return nil
	})

	promise := js.Global().Get("Promise").New(executor)

	// The Promise constructor calls the executor synchronously and never again,
	// so its slot in the Go/JS bridge goes back now. Held, it leaked one slot
	// per promise-returning call for the life of the page.
	executor.Release()

	return promise
}

// crystallineRecovered renders a recovered value without reaching for fmt,
// which would drag reflect back into the binary.
func crystallineRecovered(recovered any) string {
	switch typed := recovered.(type) {
	case string:
		return typed
	case error:
		return typed.Error()
	}

	return "panic"
}

// crystallineWrapper turns the error slot into a thrown JS Error. Go cannot
// raise a JS exception from inside a callback, so the throw has to happen on
// the JS side.
var crystallineWrapper js.Value

func crystallineWrap(fn js.Func) js.Value {
	if crystallineWrapper.IsUndefined() {
		crystallineWrapper = js.Global().Call("eval", `(fn) => (...args) => {
			const result = fn(...args);
			if (globalThis.goInternalError) {
				const error = new Error(globalThis.goInternalError);
				globalThis.goInternalError = undefined;
				throw error;
			}
			return result;
		}`)
	}

	return crystallineWrapper.Invoke(fn)
}

// crystallineIterator turns a Go channel into a JS async iterable, which is the
// same idea spelled the other language's way.
//
// next is called once per iteration and reports the value plus whether the
// channel is still open. stop tears down whatever governs the stream, and runs
// once the stream ends however it ends.
func crystallineIterator(next func() (any, bool), stop func()) any {
	var once sync.Once

	finish := func() {
		once.Do(stop)
	}

	iterator := js.Global().Get("Object").New()

	iterator.Set("next", js.FuncOf(func(this js.Value, args []js.Value) any {
		return crystallinePromise(func() any {
			result := js.Global().Get("Object").New()

			value, ok := next()
			if !ok {
				finish()

				result.Set("done", true)
				result.Set("value", nil)

				return result
			}

			result.Set("done", false)
			result.Set("value", value)

			return result
		})
	}))

	// A consumer that stops early -- breaking out of a for await -- asks the
	// iterator to return. That is the only notice Go gets that nobody is
	// reading any more, so it is where an abandoned stream is torn down.
	iterator.Set("return", js.FuncOf(func(this js.Value, args []js.Value) any {
		finish()

		result := js.Global().Get("Object").New()
		result.Set("done", true)
		result.Set("value", nil)

		return result
	}))

	iterable := js.Global().Get("Object").New()

	// Symbol.asyncIterator cannot be reached through Value.Set, which only
	// takes string keys, so the wiring is done in JS.
	js.Global().Call("eval", `(iterable, iterator) => {
		iterable[Symbol.asyncIterator] = () => iterator;
		return iterable;
	}`).Invoke(iterable, iterator)

	return iterable
}

// crystallineSource normalises anything iterable into a stepping function, so
// an array, a generator and an async generator all work the same way.
var crystallineSourceOf js.Value

func crystallineSource(source js.Value) js.Value {
	if crystallineSourceOf.IsUndefined() {
		crystallineSourceOf = js.Global().Call("eval", `(source) => {
			const iterator = source[Symbol.asyncIterator]
				? source[Symbol.asyncIterator]()
				: source[Symbol.iterator]();

			return {
				next: () => Promise.resolve(iterator.next()),
				stop: () => { if (iterator.return) { iterator.return(); } },
			};
		}`)
	}

	return crystallineSourceOf.Invoke(source)
}

// crystallineFeed drains a JS iterable into a Go channel on its own goroutine.
//
// The returned stop function ends the feed and tells the iterator no more will
// be read, so abandoning the channel does not strand the goroutine.
func crystallineFeed[T any](source js.Value, convert func(js.Value) (T, error)) (<-chan T, func() error) {
	out := make(chan T)
	done := make(chan struct{})
	finished := make(chan struct{})

	if source.IsUndefined() || source.IsNull() {
		close(out)

		return out, func() error { return nil }
	}

	iterator := crystallineSource(source)

	// failure is written before finished is closed and read after, so the close
	// orders the two.
	var failure error

	go func() {
		defer close(finished)
		defer close(out)

		for {
			step, err := crystallineAwaited(iterator.Call("next"))
			if err != nil {
				// A rejecting source used to panic here, in a goroutine with
				// no recover, which ends the program rather than the call.
				failure = err

				return
			}

			if step.Get("done").Truthy() {
				return
			}

			value, err := convert(step.Get("value"))
			if err != nil {
				// Ending the stream here would look like a clean end of input,
				// and Go would answer for the values that did arrive.
				failure = err

				return
			}

			select {
			case out <- value:
			case <-done:
				return
			}
		}
	}()

	var once sync.Once

	// Idempotent, and reports whatever ended the feed. The wrapper calls it
	// after the Go function returns and fails the call if the input was bad.
	return out, func() error {
		once.Do(func() {
			close(done)
			iterator.Call("stop")
		})

		<-finished

		return failure
	}
}

// crystallineContext bridges a JS AbortSignal to a Go context, so a call that
// would otherwise hold the single JS thread can be cancelled.
func crystallineContext(signal js.Value) (context.Context, func()) {
	ctx, cancel := context.WithCancel(context.Background())

	if signal.IsUndefined() || signal.IsNull() {
		return ctx, cancel
	}

	if signal.Get("aborted").Truthy() {
		cancel()

		return ctx, cancel
	}

	listener := js.FuncOf(func(this js.Value, args []js.Value) any {
		cancel()

		return nil
	})

	signal.Call("addEventListener", "abort", listener)

	return ctx, func() {
		signal.Call("removeEventListener", "abort", listener)
		listener.Release()
		cancel()
	}
}

// crystallineAwait resolves a thenable, so a Go caller can treat an async JS
// callback like a synchronous one. It blocks, which is safe only because a
// callback forces the enclosing call onto a goroutine.
// crystallineHandleKey names the hidden property carrying a wrapper's handle.
// It is non-enumerable, so Object.keys and JSON.stringify do not see it.
const crystallineHandleKey = "__crystallineHandle"

// Wrappers are backed by a handle table rather than by copying, so a value
// handed back to Go resolves to the object it came from. Entries are released
// when JS collects the wrapper, or when it is released explicitly.
type crystallineEntry struct {
	value any

	// cache holds the wrappers the struct-typed fields handed out, so that a
	// field read twice gives the same object. It goes when the entry does.
	cache map[int]crystallineCacheSlot
}

type crystallineCacheSlot struct {
	key   any
	value any
}

var (
	crystallineHandleMutex sync.Mutex
	crystallineHandles     = make(map[int]*crystallineEntry)
	crystallineHandleNext  int
)

func crystallineRetain(value any) int {
	crystallineHandleMutex.Lock()
	defer crystallineHandleMutex.Unlock()

	crystallineHandleNext++
	crystallineHandles[crystallineHandleNext] = &crystallineEntry{value: value}

	return crystallineHandleNext
}

func crystallineResolve(handle int) (any, bool) {
	crystallineHandleMutex.Lock()
	defer crystallineHandleMutex.Unlock()

	entry, ok := crystallineHandles[handle]
	if !ok {
		return nil, false
	}

	return entry.value, true
}

// crystallineReleaseHandle drops a wrapper's entry. Nothing else is held per
// wrapper: its accessors and methods belong to its type.
func crystallineReleaseHandle(handle int) {
	crystallineHandleMutex.Lock()
	delete(crystallineHandles, handle)
	crystallineHandleMutex.Unlock()
}

// crystallineCached hands back the wrapper a struct-typed field produced the
// last time it was read, building a new one only when key changed.
//
// Rebuilding it on every read allocated a handle each time, and meant
// a.Field !== a.Field, which breaks ===, Map keys and every framework's memo
// comparison. A field held by value has a stable address, so its key is nil and
// never changes. A pointer field is keyed on the pointer, so it refreshes when
// Go points elsewhere.
func crystallineCached(entry *crystallineEntry, field int, key any, build func() any) any {
	crystallineHandleMutex.Lock()
	slot, ok := entry.cache[field]
	crystallineHandleMutex.Unlock()

	if ok && slot.key == key {
		return slot.value
	}

	value := build()

	crystallineHandleMutex.Lock()
	if entry.cache == nil {
		entry.cache = make(map[int]crystallineCacheSlot)
	}
	entry.cache[field] = crystallineCacheSlot{key: key, value: value}
	crystallineHandleMutex.Unlock()

	return value
}

// crystallineShaper turns one type's accessors and methods into a function
// that builds its wrappers. It is compiled once.
//
// A wrapper keeps the shape it always had: its fields as enumerable accessor
// properties, its methods and release as enumerable functions, all its own, so
// Object.keys, JSON.stringify and a walk over its properties see what they
// did. What changed is who owns the functions. The accessors are shared by the
// type and read the handle off the object they are called on, and a method is
// a JavaScript closure over the handle rather than a bridge slot of its own.
var crystallineShaper js.Value

// crystallineReleaser is the release every wrapper shares, and the finalizer's
// callback: both are handed the handle.
var crystallineReleaser js.Func

var crystallineFinalizer js.Value

// crystallineShape builds the factory for one type's wrappers.
//
// It costs three js.FuncOf per type, once. A wrapper then costs one call into
// JavaScript, where it used to cost two js.FuncOf per field, one per method and
// one for release, plus a call to define each of them.
func crystallineShape[T any](
	subject string,
	fields []string,
	get func(v *T, entry *crystallineEntry, field int) any,
	set func(v *T, field int, value js.Value),
	methods []string,
	call func(v *T, method int, args []js.Value) any,
) js.Value {
	if crystallineShaper.IsUndefined() {
		crystallineShaper = js.Global().Call("eval", `(key, fields, get, set, methods, call, release, registry) => {
			const descriptors = {};
			fields.forEach((name, i) => {
				descriptors[name] = {
					enumerable: true,
					// Configurable so a wrapper that cannot accept writes can
					// replace the setter after the fact. See crystallineFrozen.
					configurable: true,
					get() { return get(this[key], i); },
					set(value) { set(this[key], i, value); },
				};
			});
			const disposable = typeof Symbol.dispose !== "undefined";
			return (handle) => {
				const out = Object.defineProperties({}, descriptors);
				methods.forEach((name, m) => {
					out[name] = (...args) => call(handle, m, ...args);
				});
				Object.defineProperty(out, key, { value: handle, enumerable: false });
				// Explicit disposal, so a caller that knows when it is done
				// need not wait for the collector.
				const dispose = () => release(handle);
				out.release = dispose;
				if (disposable) {
					out[Symbol.dispose] = dispose;
				}
				if (registry !== undefined) {
					registry.register(out, handle);
				}
				return out;
			};
		}`)

		crystallineReleaser = js.FuncOf(func(this js.Value, args []js.Value) any {
			if len(args) > 0 && args[0].Type() == js.TypeNumber {
				crystallineReleaseHandle(args[0].Int())
			}

			return nil
		})

		if constructor := js.Global().Get("FinalizationRegistry"); !constructor.IsUndefined() {
			crystallineFinalizer = constructor.New(crystallineReleaser)
		}
	}

	// entryOf finds what a handle stands for. A released wrapper still has its
	// accessors, since they belong to the type, so this is where it is told.
	entryOf := func(handle js.Value) (*T, *crystallineEntry, error) {
		if handle.Type() != js.TypeNumber {
			return nil, nil, errors.New(subject + ": called on something that is not its wrapper")
		}

		crystallineHandleMutex.Lock()
		entry, ok := crystallineHandles[handle.Int()]
		crystallineHandleMutex.Unlock()

		if !ok {
			return nil, nil, errors.New(subject + ": the value behind this handle has been released")
		}

		return entry.value.(*T), entry, nil
	}

	getter := js.FuncOf(func(this js.Value, args []js.Value) (result any) {
		defer crystallineRecover(&result)

		v, entry, err := entryOf(args[0])
		if err != nil {
			return crystallineFail(err.Error())
		}

		return get(v, entry, args[1].Int())
	})

	// A write validates, so it throws where it happened rather than poisoning
	// the next unrelated call.
	setter := js.FuncOf(func(this js.Value, args []js.Value) (result any) {
		defer crystallineRecover(&result)

		v, _, err := entryOf(args[0])
		if err != nil {
			return crystallineFail(err.Error())
		}

		set(v, args[1].Int(), args[2])

		return nil
	})

	caller := js.FuncOf(func(this js.Value, args []js.Value) (result any) {
		defer crystallineRecover(&result)

		v, _, err := entryOf(args[0])
		if err != nil {
			return crystallineFail(err.Error())
		}

		return call(v, args[1].Int(), args[2:])
	})

	names := func(list []string) []any {
		out := make([]any, 0, len(list))
		for _, name := range list {
			out = append(out, name)
		}

		return out
	}

	return crystallineShaper.Invoke(crystallineHandleKey, names(fields), crystallineWrap(getter), crystallineWrap(setter),
		names(methods), crystallineWrap(caller), crystallineReleaser, crystallineFinalizer)
}

// crystallineHandleOf recovers the handle a wrapper carries, if any.
func crystallineHandleOf(value js.Value) (int, bool) {
	if value.Type() != js.TypeObject {
		return 0, false
	}

	handle := value.Get(crystallineHandleKey)
	if handle.Type() != js.TypeNumber {
		return 0, false
	}

	return handle.Int(), true
}

// crystallineUnknownProperty reports a property the target type does not have,
// so that a misspelling fails instead of silently leaving a zero value.
func crystallineUnknownProperty(value js.Value, typeName string, known map[string]bool) error {
	keys := js.Global().Get("Object").Call("keys", value)

	for i := 0; i < keys.Length(); i++ {
		name := keys.Index(i).String()
		if !known[name] {
			return errors.New(typeName + ": unknown property " + strconv.Quote(name))
		}
	}

	return nil
}

// crystallineAwait resolves a thenable and panics if it rejects, which is the
// only answer in a function whose Go signature belongs to the consumer.
func crystallineAwait(value js.Value) js.Value {
	resolved, err := crystallineAwaited(value)
	if err != nil {
		panic(err.Error())
	}

	return resolved
}

// crystallineAwaited is the same wait for a caller that has somewhere to report
// a rejection to. A feed does: it already carries whatever ended it.
func crystallineAwaited(value js.Value) (js.Value, error) {
	if !crystallineIsThenable(value) {
		return value, nil
	}

	settled := make(chan js.Value, 1)
	failed := make(chan string, 1)

	onResolved := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) == 0 {
			settled <- js.Undefined()
		} else {
			settled <- args[0]
		}

		return nil
	})
	defer onResolved.Release()

	onRejected := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) == 0 {
			failed <- "promise rejected"
		} else {
			failed <- crystallineErrorText(args[0])
		}

		return nil
	})
	defer onRejected.Release()

	value.Call("then", onResolved, onRejected)

	select {
	case result := <-settled:
		return result, nil
	case message := <-failed:
		return js.Undefined(), errors.New(message)
	}
}

// crystallineErrorText renders whatever a promise rejected with. Value.String()
// on an Error object gives the literal "<object>", which names nothing, and
// that is what a rejection almost always carries.
func crystallineErrorText(value js.Value) string {
	if value.Type() == js.TypeObject {
		if message := value.Get("message"); message.Type() == js.TypeString {
			return message.String()
		}
	}

	return value.String()
}

// crystallineFreezer replaces the setters of an already-built wrapper with one
// that refuses. It is compiled once, and freezing is one call however many
// fields the wrapper has.
var crystallineFreezer js.Value

// crystallineFrozen makes an already-built wrapper reject writes.
//
// A Go map element has no address, so the wrapper stands over a copy of it. A
// write would reach the copy and be discarded, which is worse than refusing it:
// the caller has no way to tell. Reads and methods are left alone, because they
// read the copy correctly.
func crystallineFrozen(value any) any {
	object, ok := value.(js.Value)
	if !ok {
		return value
	}

	if crystallineFreezer.IsUndefined() {
		crystallineFreezer = js.Global().Call("eval", `(() => {
			const refuse = () => {
				throw new Error("cannot be written: a map element is a copy in Go, so the write would be discarded");
			};
			return (object) => {
				for (const name of Object.keys(object)) {
					const descriptor = Object.getOwnPropertyDescriptor(object, name);
					// A method is a plain property: there is no write to refuse.
					if (descriptor.set === undefined) {
						continue;
					}
					Object.defineProperty(object, name, {
						enumerable: true,
						configurable: true,
						get: descriptor.get,
						set: refuse,
					});
				}
			};
		})()`)
	}

	crystallineFreezer.Invoke(object)

	return value
}

// crystallineRecover turns a panic into a reported failure, so a bad argument
// surfaces as a thrown Error rather than tearing down the wasm runtime.
func crystallineRecover(result *any) {
	if recovered := recover(); recovered != nil {
		*result = crystallineFail(crystallineRecovered(recovered))
	}
}

// crystallineIsThenable reports whether a value is something to await.
//
// It asks for the tag before touching the value, because Value.Type panics with
// "bad type flag" on a BigInt and Get checks the type first. A method returning
// a bigint used to crash here rather than being awaited or not.
func crystallineIsThenable(value js.Value) bool {
	tag := js.Global().Get("Object").Get("prototype").Get("toString").Call("call", value).String()
	if tag != "[object Promise]" && tag != "[object Object]" {
		return false
	}

	return value.Get("then").Type() == js.TypeFunction
}

// crystallineDirect is the result of an imported method that was not declared
// to return a promise.
//
// Awaiting one anyway would block this goroutine, and a goroutine blocked
// inside a synchronous js.FuncOf hands JavaScript undefined and finishes the
// work afterwards: a wrong answer rather than a slow one. There is nowhere to
// report to — the Go signature belongs to the consumer — so this is one of the
// few places left that panics.
func crystallineDirect(value js.Value, subject string) js.Value {
	if crystallineIsThenable(value) {
		panic(subject + " returned a promise, and it was not declared with bind.AsPromise")
	}

	return value
}

// crystallineResolvePath walks a dotted path from the JavaScript global object,
// so an import says where it lives rather than being handed in.
func crystallineResolvePath(path string) (js.Value, error) {
	at := js.Global()

	start := 0
	for i := 0; i <= len(path); i++ {
		if i < len(path) && path[i] != '.' {
			continue
		}

		segment := path[start:i]
		start = i + 1

		at = at.Get(segment)
		if at.IsUndefined() || at.IsNull() {
			return js.Undefined(), errors.New(path + " is not there: " + segment + " is missing")
		}
	}

	return at, nil
}

// crystallineImportFailed records an import that could not be filled.
//
// It cannot report the way a call does, because nothing is calling: this runs
// while the program starts. The failures are published instead, and the
// generated module refuses to hand over a surface that is missing part of
// itself, which turns a null pointer at the first use into a message at the
// boot that caused it.
var crystallineImportFailures []string

func crystallineImportFailed(subject string, err error) {
	crystallineImportFailures = append(crystallineImportFailures, subject+": "+err.Error())
}

func crystallinePublishImportFailures(app string) {
	if len(crystallineImportFailures) == 0 {
		return
	}

	reported := make([]any, 0, len(crystallineImportFailures))
	for _, failure := range crystallineImportFailures {
		reported = append(reported, failure)
	}

	crystallineNamespace(app, "__crystalline").Set("importFailures", reported)
}

// crystallineBigInt and crystallineBigUint hand a 64-bit integer over as a
// JavaScript BigInt, which carries it exactly where a number cannot.
func crystallineBigInt(value int64) any {
	return js.Global().Get("BigInt").Invoke(strconv.FormatInt(value, 10))
}

func crystallineBigUint(value uint64) any {
	return js.Global().Get("BigInt").Invoke(strconv.FormatUint(value, 10))
}

// crystallineBigIntText reads the digits of a JavaScript BigInt, and reports
// whether it was one.
//
// Nothing here may look at the value through syscall/js. Value.Type panics with
// "bad type flag" on a BigInt — there is no type constant for one — and Get and
// Call check the type first, so even asking what it is crashes. JavaScript is
// asked instead, through calls that only pass the reference along.
func crystallineBigIntText(value js.Value) (string, bool) {
	tag := js.Global().Get("Object").Get("prototype").Get("toString").Call("call", value)
	if tag.String() != "[object BigInt]" {
		return "", false
	}

	return js.Global().Get("String").Invoke(value).String(), true
}

func crystallineToBigInt(value js.Value) (int64, error) {
	text, ok := crystallineBigIntText(value)
	if !ok {
		return 0, errors.New("expected a bigint")
	}

	parsed, err := strconv.ParseInt(text, 10, 64)
	if err != nil {
		return 0, errors.New(text + " does not fit in an int64")
	}

	return parsed, nil
}

func crystallineToBigUint(value js.Value) (uint64, error) {
	text, ok := crystallineBigIntText(value)
	if !ok {
		return 0, errors.New("expected a bigint")
	}

	parsed, err := strconv.ParseUint(text, 10, 64)
	if err != nil {
		return 0, errors.New(text + " does not fit in a uint64")
	}

	return parsed, nil
}

// crystallineOk and crystallineErr build the Result a fallible call returns.
// Failure travels in the value, so a call that can fail need not be async.
// crystallineResultProto carries the Result methods. They live on a prototype
// built once rather than on each result: attaching js.Func values per call
// would allocate a bridge slot for every fallible call and leak it.
var crystallineResultProto js.Value

func crystallineResultPrototype() js.Value {
	if crystallineResultProto.IsUndefined() {
		crystallineResultProto = js.Global().Call("eval", `({
			unwrap() {
				if (this.ok) {
					return this.value;
				}
				throw this.error;
			},
			unwrapOr(fallback) {
				return this.ok ? this.value : fallback;
			},
		})`)
	}

	return crystallineResultProto
}

func crystallineOk(value any) any {
	out := js.Global().Get("Object").Call("create", crystallineResultPrototype())
	out.Set("ok", true)
	out.Set("value", value)

	return out
}

func crystallineErr(err error) any {
	out := js.Global().Get("Object").Call("create", crystallineResultPrototype())
	out.Set("ok", false)
	out.Set("error", js.Global().Get("Error").New(err.Error()))

	return out
}

func crystallineError(err error) any {
	if err == nil {
		return nil
	}

	return js.Global().Get("Error").New(err.Error())
}

func crystallineFnLedgerAdd(this js.Value, args []js.Value) (result any) {
	defer crystallineRecover(&result)

	if len(args) != 2 {
		return crystallineFail("Add: expected 2 arguments, got " + strconv.Itoa(len(args)))
	}

	a0, err := crystallineToString(args[0])
	if err != nil {
		return crystallineFail(err.Error())
	}

	a1, err := crystallineToInt(args[1])
	if err != nil {
		return crystallineFail(err.Error())
	}

	r0 := ledger.Add(a0, a1)

	return crystallineMarshalLedgerEntry(&r0)
}

func crystallineFnLedgerBalance(this js.Value, args []js.Value) (result any) {
	defer crystallineRecover(&result)

	if len(args) != 0 {
		return crystallineFail("Balance: expected 0 arguments, got " + strconv.Itoa(len(args)))
	}

	r0 := ledger.Balance()

	return float64(r0)
}

func crystallineFnLedgerForget(this js.Value, args []js.Value) (result any) {
	defer crystallineRecover(&result)

	if len(args) != 0 {
		return crystallineFail("Forget: expected 0 arguments, got " + strconv.Itoa(len(args)))
	}

	ledger.Forget()

	return nil
}

var crystallineMarshalLedgerEntryShape js.Value

func crystallineMarshalLedgerEntry(v *ledger.Entry) any {
	if v == nil {
		return nil
	}

	if crystallineMarshalLedgerEntryShape.IsUndefined() {
		crystallineMarshalLedgerEntryShape = crystallineShape("ledger.Entry",
			[]string{"id", "description", "amount"},
			func(v *ledger.Entry, entry *crystallineEntry, field int) any {
				switch field {
				case 0:
					return crystallineBigInt(int64(v.ID))
				case 1:
					return string(v.Note)
				case 2:
					return float64(v.Amount)
				}

				return nil
			},
			func(v *ledger.Entry, field int, value js.Value) {
				switch field {
				case 0:
					(func(value js.Value) {
						converted, err := crystallineToBigInt(value)
						if err != nil {
							crystallineFail(err.Error())

							return
						}

						v.ID = int64(converted)
					})(value)
				case 1:
					(func(value js.Value) {
						converted, err := crystallineToString(value)
						if err != nil {
							crystallineFail(err.Error())

							return
						}

						v.Note = converted
					})(value)
				case 2:
					(func(value js.Value) {
						converted, err := crystallineToInt(value)
						if err != nil {
							crystallineFail(err.Error())

							return
						}

						v.Amount = converted
					})(value)
				}
			},
			[]string{},
			func(v *ledger.Entry, method int, args []js.Value) any {
				switch method {
				}

				return nil
			},
		)
	}

	return crystallineMarshalLedgerEntryShape.Invoke(crystallineRetain(v))
}

func crystallineToInt(value js.Value) (int, error) {
	var zero int

	if value.Type() != js.TypeNumber {
		return zero, errors.New("expected a number")
	}

	return int(value.Float()), nil
}

func crystallineToString(value js.Value) (string, error) {
	var zero string

	if value.Type() != js.TypeString {
		return zero, errors.New("expected a string")
	}

	return string(value.String()), nil
}

type crystallineImportedStore struct{ value js.Value }

func (c crystallineImportedStore) GetItem(p0 string) string {
	crystallineSupplied := crystallineDirect(c.value.Call("getItem", string(p0)), "ledger.Store.GetItem")

	crystallineConverted, err := crystallineToString(crystallineSupplied)
	if err != nil {
		panic("ledger.Store.GetItem: result: " + err.Error())
	}

	return crystallineConverted
}

func (c crystallineImportedStore) SetItem(p0 string, p1 string) {
	crystallineDirect(c.value.Call("setItem", string(p0), string(p1)), "ledger.Store.SetItem")
}

func crystallineImportLedgerStore(value js.Value) (ledger.Store, error) {
	if value.Type() != js.TypeObject {
		return nil, errors.New("ledger.Store: expected an object")
	}

	if value.Get("getItem").Type() != js.TypeFunction {
		return nil, errors.New("ledger.Store: the object has no getItem method")
	}

	if value.Get("setItem").Type() != js.TypeFunction {
		return nil, errors.New("ledger.Store: the object has no setItem method")
	}

	return crystallineImportedStore{value: value}, nil
}
